//! Exact Base64-text fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{CesrError, bexter::Base64Text, code::DerivationCode, matter::QualifiedMaterial};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    cases: Vec<Case>,
    boundary_cases: Vec<BoundaryCase>,
    stream_case: StreamCase,
    reference_quirks: ReferenceQuirks,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    input: String,
    canonical_text: String,
    code: String,
    size: u32,
    both: String,
    raw_hex: String,
    qb64: String,
    qb64_bytes_hex: String,
    qb2_hex: String,
    parsed_canonical_text: String,
}

#[derive(Debug, Deserialize)]
struct BoundaryCase {
    name: String,
    code: String,
    size: u32,
    both: String,
    raw_hex: String,
    qb64: String,
    qb2_hex: String,
    parsed_text_matches_input: bool,
    input_pattern: String,
    input_length: usize,
}

#[derive(Debug, Deserialize)]
struct StreamCase {
    input: String,
    declared_material_characters: usize,
    rust_parsed_canonical_text: String,
    reference_observed_canonical_text: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    truncated_qb64_acceptance: TruncatedAcceptance,
}

#[derive(Debug, Deserialize)]
struct TruncatedAcceptance {
    input: String,
    observed_code: String,
    observed_raw_hex: String,
    observed_canonical_text: String,
    reencode_error_category: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-bexter/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_complete() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/bexter.ts",
            "src/keri/core/matter.ts",
            "src/keri/core/base64.ts",
            "test/core/bexter.test.ts",
            "test/core/pather.test.ts",
        ]
    );
    assert!(fixture.binary_derivation.contains("_bexfil is unimplemented"));
    assert_eq!(fixture.cases.len(), 13);
    assert_eq!(fixture.boundary_cases.len(), 2);
    assert_eq!(fixture.rejected_cases.len(), 7);
    Ok(())
}

#[test]
fn all_reference_examples_match_exactly_in_every_domain() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        let raw = decode_hex(&case.raw_hex)?;
        let qb64_bytes = decode_hex(&case.qb64_bytes_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let value = Base64Text::new(&case.input)?;
        assert_eq!(value.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(
            value.variable_size(),
            Some(case.size),
            "size mismatch for {}",
            case.name
        );
        assert_eq!(value.both()?, case.both, "leader mismatch for {}", case.name);
        assert_eq!(value.raw(), raw, "raw mismatch for {}", case.name);
        assert_eq!(value.text()?, case.canonical_text, "text mismatch for {}", case.name);
        assert_eq!(value.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(value.qb64_bytes()?, qb64_bytes, "qb64 bytes mismatch for {}", case.name);
        assert_eq!(value.qb2()?, qb2, "qb2 mismatch for {}", case.name);

        let from_qb64 = Base64Text::from_qb64(&case.qb64)?;
        let from_qb2 = Base64Text::from_qb2(&qb2)?;
        assert_eq!(from_qb64.text()?, case.parsed_canonical_text);
        assert_eq!(from_qb2, from_qb64);
    }
    Ok(())
}

#[test]
fn small_to_large_boundary_matches_complete_reference_artifacts() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.boundary_cases {
        assert_eq!(case.input_pattern.len(), 1, "invalid pattern for {}", case.name);
        let input = case.input_pattern.repeat(case.input_length);
        let raw = decode_hex(&case.raw_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let value = Base64Text::new(&input)?;
        assert_eq!(value.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(
            value.variable_size(),
            Some(case.size),
            "size mismatch for {}",
            case.name
        );
        assert_eq!(value.both()?, case.both, "leader mismatch for {}", case.name);
        assert_eq!(value.raw(), raw, "raw mismatch for {}", case.name);
        assert_eq!(value.text()?, input, "text mismatch for {}", case.name);
        assert_eq!(value.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(value.qb64_bytes()?, case.qb64.as_bytes());
        assert_eq!(value.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert!(case.parsed_text_matches_input);
        assert_eq!(Base64Text::from_qb64(&case.qb64)?.text()?, input);
        assert_eq!(Base64Text::from_qb2(&qb2)?, value);
    }
    Ok(())
}

#[test]
fn stream_and_truncation_quirks_are_explicit_safe_divergences() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let stream = fixture.stream_case;
    let parsed = Base64Text::parse_qb64(&stream.input)?;
    assert_eq!(parsed.consumed(), stream.declared_material_characters);
    assert_eq!(parsed.value().text()?, stream.rust_parsed_canonical_text);
    assert_ne!(
        stream.reference_observed_canonical_text,
        stream.rust_parsed_canonical_text
    );
    assert!(matches!(
        Base64Text::from_qb64(&stream.input),
        Err(CesrError::TrailingMaterial { .. })
    ));

    let truncated = fixture.reference_quirks.truncated_qb64_acceptance;
    assert_eq!(truncated.observed_code, "4A");
    assert_eq!(truncated.observed_raw_hex, "");
    assert_eq!(truncated.observed_canonical_text, "");
    assert_eq!(truncated.reencode_error_category, "RangeError");
    let error = Base64Text::from_qb64(&truncated.input)
        .err()
        .ok_or("truncated Base64-text material was accepted")?;
    assert_eq!(error_category(&error), truncated.rust_error_category);
    Ok(())
}

#[test]
fn reference_rejections_and_rust_qb2_completion_are_recorded() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    for case in &fixture.rejected_cases {
        assert_ne!(case.reference_error_category, "");
        assert_ne!(case.reference_error_message, "");
        match case.name.as_str() {
            "missing_text" => assert_eq!(case.rust_error_category, "Unrepresentable"),
            "invalid_alphabet" => assert_rejected_text("@!", case)?,
            "standard_alphabet" => assert_rejected_text("+/", case)?,
            "padding_character" => assert_rejected_text("AA=", case)?,
            "wrong_raw_code" => {
                let error = Base64Text::from_raw(DerivationCode::BLAKE3_256, &[0_u8; 32])
                    .err()
                    .ok_or("wrong raw code was accepted")?;
                assert_eq!(error_category(&error), case.rust_error_category);
            }
            "wrong_qb64_code" => {
                let matter = QualifiedMaterial::new(DerivationCode::BLAKE3_256, &[0_u8; 32])?;
                let error = Base64Text::from_qb64(&matter.qb64()?)
                    .err()
                    .ok_or("wrong qb64 code was accepted")?;
                assert_eq!(error_category(&error), case.rust_error_category);
            }
            "qb2_constructor" => {
                assert_eq!(case.rust_error_category, "ReferenceUnsupported");
                let source = fixture
                    .cases
                    .iter()
                    .find(|candidate| candidate.name == "dependent_path_shape")
                    .ok_or("missing qb2 completion source case")?;
                let value = Base64Text::from_qb2(&decode_hex(&source.qb2_hex)?)?;
                assert_eq!(value.text()?, source.canonical_text);
            }
            name => return Err(format!("unknown rejected fixture case {name}").into()),
        }
    }
    Ok(())
}

fn assert_rejected_text(input: &str, case: &RejectedCase) -> Result<(), Box<dyn Error>> {
    let error = Base64Text::new(input)
        .err()
        .ok_or("reference-rejected text was accepted")?;
    assert_eq!(error_category(&error), case.rust_error_category);
    Ok(())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::InvalidBase64Character { .. } => "InvalidBase64Character",
        CesrError::InvalidBase64TextCode { .. } => "InvalidBase64TextCode",
        CesrError::Truncated { .. } => "Truncated",
        _ => "Unexpected",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let (pairs, remainder) = input.as_bytes().as_chunks::<2>();
    if !remainder.is_empty() {
        return Err("odd-length hexadecimal fixture".into());
    }
    pairs
        .iter()
        .map(|chunk| {
            let text = std::str::from_utf8(chunk)?;
            Ok(u8::from_str_radix(text, 16)?)
        })
        .collect()
}
