//! Exact ciphertext-material fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use serde::Deserialize;
use signify_cesr::{CesrError, code::DerivationCode, matter::QualifiedMaterial};
use signify_crypto::{
    CryptoError,
    cipher::{Ciphertext, CiphertextKind, SALT_CIPHERTEXT_RAW_SIZE, SEED_CIPHERTEXT_RAW_SIZE},
};

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    cases: Vec<CipherCase>,
    rejected_cases: Vec<RejectedCase>,
    reference_quirks: ReferenceQuirks,
}

#[derive(Debug, Deserialize)]
struct CipherCase {
    name: String,
    plaintext_kind: String,
    code: String,
    raw_hex: String,
    raw_size: usize,
    qb64: String,
    qb64_bytes_hex: String,
    qb2_hex: String,
    qb64_round_trip: String,
    raw_round_trip: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    excess_seed_raw_truncation: ExcessRawQuirk,
    excess_salt_raw_truncation: ExcessRawQuirk,
    raw_seed_inference_misclassifies_and_truncates: SeedInferenceQuirk,
    raw_salt_inference: SaltInferenceQuirk,
}

#[derive(Debug, Deserialize)]
struct ExcessRawQuirk {
    input_raw_hex: String,
    retained_raw_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct SeedInferenceQuirk {
    input_raw_hex: String,
    reference_code: String,
    retained_raw_hex: String,
    qb64: String,
    rust_code: String,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct SaltInferenceQuirk {
    input_raw_hex: String,
    reference_code: String,
    retained_raw_hex: String,
    qb64: String,
    rust_code: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/crypto-cipher/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-14");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/cipher.ts",
            "src/keri/core/matter.ts",
            "test/core/encrypter.test.ts",
            "test/core/decrypter.test.ts",
        ]
    );
    assert!(fixture.binary_derivation.contains("Matter._bexfil"));
    Ok(())
}

#[test]
fn successful_reference_cases_match_exact_outputs() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        let raw = decode_hex(&case.raw_hex)?;
        let qb64_bytes = decode_hex(&case.qb64_bytes_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let kind = match case.plaintext_kind.as_str() {
            "qualified_seed" => CiphertextKind::QualifiedSeed,
            "qualified_salt" => CiphertextKind::QualifiedSalt,
            other => return Err(format!("unknown ciphertext kind {other}").into()),
        };
        let ciphertext = Ciphertext::from_raw(kind, &raw)?;

        assert_eq!(ciphertext.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(
            ciphertext.raw().len(),
            case.raw_size,
            "raw size mismatch for {}",
            case.name
        );
        assert_eq!(ciphertext.raw(), raw, "raw mismatch for {}", case.name);
        assert_eq!(ciphertext.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(
            ciphertext.qb64_bytes()?,
            qb64_bytes,
            "qb64 bytes mismatch for {}",
            case.name
        );
        assert_eq!(ciphertext.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert_eq!(
            case.qb64_round_trip, case.qb64,
            "reference qb64 round trip for {}",
            case.name
        );
        assert_eq!(
            case.raw_round_trip, case.qb64,
            "reference raw round trip for {}",
            case.name
        );
        assert_eq!(Ciphertext::from_qb64(&case.qb64)?, ciphertext);
        assert_eq!(Ciphertext::from_qb64_bytes(&qb64_bytes)?, ciphertext);
        assert_eq!(Ciphertext::from_qb2(&qb2)?, ciphertext);
        assert_eq!(Ciphertext::infer_from_raw(&raw)?, ciphertext);
    }
    Ok(())
}

#[test]
fn reference_rejections_map_to_typed_or_safe_rust_behavior() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let first_case = fixture.cases.first().ok_or("cipher fixture has no successful case")?;
    for case in &fixture.rejected_cases {
        assert!(!case.reference_error_category.is_empty());
        assert!(!case.reference_error_message.is_empty());
        let category = match case.name.as_str() {
            "empty_material" => {
                crypto_error_category(&Ciphertext::from_qb64("").err().ok_or("empty ciphertext was accepted")?)
            }
            "short_seed_ciphertext" => crypto_error_category(
                &Ciphertext::from_raw(CiphertextKind::QualifiedSeed, &[0_u8; SEED_CIPHERTEXT_RAW_SIZE - 1])
                    .err()
                    .ok_or("short seed ciphertext was accepted")?,
            ),
            "short_salt_ciphertext" => crypto_error_category(
                &Ciphertext::from_raw(CiphertextKind::QualifiedSalt, &[0_u8; SALT_CIPHERTEXT_RAW_SIZE - 1])
                    .err()
                    .ok_or("short salt ciphertext was accepted")?,
            ),
            "non_cipher_code" => {
                let digest = QualifiedMaterial::new(DerivationCode::BLAKE3_256, &[0_u8; 32])?;
                crypto_error_category(
                    &Ciphertext::from_qb64(&digest.qb64()?)
                        .err()
                        .ok_or("non-cipher code was accepted")?,
                )
            }
            "qb2_constructor" => {
                let qb2 = decode_hex(&first_case.qb2_hex)?;
                assert_eq!(Ciphertext::from_qb2(&qb2)?.qb64()?, first_case.qb64);
                "ReferenceUnsupported"
            }
            other => return Err(format!("unknown rejected fixture case {other}").into()),
        };
        assert_eq!(
            category, case.rust_error_category,
            "category mismatch for {}",
            case.name
        );
    }
    Ok(())
}

#[test]
fn defective_reference_quirks_are_strictly_diverged() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    for (kind, quirk) in [
        (CiphertextKind::QualifiedSeed, quirks.excess_seed_raw_truncation),
        (CiphertextKind::QualifiedSalt, quirks.excess_salt_raw_truncation),
    ] {
        let input = decode_hex(&quirk.input_raw_hex)?;
        let retained = decode_hex(&quirk.retained_raw_hex)?;
        let retained_ciphertext = Ciphertext::from_raw(kind, &retained)?;
        assert_eq!(retained_ciphertext.qb64()?, quirk.qb64);
        let error = Ciphertext::from_raw(kind, &input)
            .err()
            .ok_or("excess raw ciphertext was silently truncated")?;
        assert_eq!(crypto_error_category(&error), quirk.rust_error_category);
    }

    let seed = quirks.raw_seed_inference_misclassifies_and_truncates;
    let seed_input = decode_hex(&seed.input_raw_hex)?;
    let reference_retained = decode_hex(&seed.retained_raw_hex)?;
    assert_eq!(seed.reference_code, "1AAH");
    assert_eq!(reference_retained.len(), SALT_CIPHERTEXT_RAW_SIZE);
    assert_eq!(Ciphertext::from_qb64(&seed.qb64)?.kind(), CiphertextKind::QualifiedSalt);
    assert_eq!(seed.rust_code, "P");
    assert!(!seed.rust_decision.is_empty());
    let rust_inferred = Ciphertext::infer_from_raw(&seed_input)?;
    assert_eq!(rust_inferred.kind(), CiphertextKind::QualifiedSeed);
    assert_eq!(rust_inferred.raw(), seed_input);

    let salt = quirks.raw_salt_inference;
    let salt_input = decode_hex(&salt.input_raw_hex)?;
    let reference_retained = decode_hex(&salt.retained_raw_hex)?;
    assert_eq!(salt.reference_code, "1AAH");
    assert_eq!(salt.rust_code, "1AAH");
    assert_eq!(reference_retained, salt_input);
    let rust_inferred = Ciphertext::infer_from_raw(&salt_input)?;
    assert_eq!(rust_inferred.kind(), CiphertextKind::QualifiedSalt);
    assert_eq!(rust_inferred.qb64()?, salt.qb64);
    Ok(())
}

fn crypto_error_category(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::Cesr { source } => match source.as_ref() {
            CesrError::EmptyInput { .. } => "EmptyInput",
            CesrError::Truncated { .. } => "Truncated",
            CesrError::TrailingMaterial { .. } => "TrailingMaterial",
            _ => "Cesr",
        },
        CryptoError::InvalidCiphertextCode { .. } => "InvalidCiphertextCode",
        CryptoError::InvalidCiphertextLength { .. } => "InvalidCiphertextLength",
        _ => "Other",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex fixture has odd length".into());
    }
    input
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| match pair {
            [high, low] => Ok((decode_nibble(*high)? << 4) | decode_nibble(*low)?),
            _ => Err("hex fixture chunk did not contain two bytes".into()),
        })
        .collect()
}

fn decode_nibble(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err(format!("invalid hex byte 0x{byte:02x}").into()),
    }
}
