//! Exact derivation-code table fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{
    CesrError,
    code::{CodeFamily, DerivationCode, hard_code_size},
};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    sizage_constructor_case: SizageCase,
    codes: Vec<CodeCase>,
    hard_selectors: Vec<HardSelectorCase>,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct SizageCase {
    input: Vec<usize>,
    hard_size: usize,
    soft_size: usize,
    full_size: usize,
    lead_size: usize,
}

#[derive(Debug, Deserialize)]
struct CodeCase {
    code: String,
    hard_size: usize,
    soft_size: usize,
    full_size: Option<usize>,
    lead_size: usize,
    raw_size: Option<usize>,
    families: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct HardSelectorCase {
    selector: String,
    hard_size: usize,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    operation: String,
    input: String,
    hard_code: String,
    reference_error_category: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-code-tables/v1.json"
    )))
}

#[test]
fn fixture_metadata_and_sizage_order_are_pinned() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(fixture.sources, ["src/keri/core/matter.ts", "test/core/matter.test.ts"]);
    assert_eq!(fixture.sizage_constructor_case.input, [1, 2, 3, 4]);
    assert_eq!(fixture.sizage_constructor_case.hard_size, 1);
    assert_eq!(fixture.sizage_constructor_case.soft_size, 2);
    assert_eq!(fixture.sizage_constructor_case.full_size, 3);
    assert_eq!(fixture.sizage_constructor_case.lead_size, 4);
    Ok(())
}

#[test]
fn complete_code_table_and_family_membership_match_exactly() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.codes.len(), DerivationCode::ALL.len());

    for (case, code) in fixture.codes.iter().zip(DerivationCode::ALL) {
        assert_eq!(code.as_str(), case.code);
        assert_eq!(code.size().hard_size(), case.hard_size);
        assert_eq!(code.size().soft_size(), case.soft_size);
        assert_eq!(code.size().full_size(), case.full_size);
        assert_eq!(code.size().lead_size(), case.lead_size);
        assert_eq!(code.size().raw_size(), case.raw_size);

        for (name, family) in [
            ("general_matter", CodeFamily::GeneralMatter),
            ("non_transferable", CodeFamily::NonTransferable),
            ("digest", CodeFamily::Digest),
            ("numeric", CodeFamily::Numeric),
            ("base64_text", CodeFamily::Base64Text),
        ] {
            assert_eq!(
                code.belongs_to(family),
                case.families.iter().any(|candidate| candidate == name),
                "family mismatch for code {} and family {name}",
                code.as_str()
            );
        }
    }
    Ok(())
}

#[test]
fn hard_selector_table_matches_exactly() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.hard_selectors.len(), 62);
    for case in fixture.hard_selectors {
        let bytes = case.selector.as_bytes();
        let selector = bytes.first().copied().ok_or("empty selector fixture")?;
        assert_eq!(bytes.len(), 1);
        assert_eq!(hard_code_size(selector)?, case.hard_size);
    }
    Ok(())
}

#[test]
fn reference_rejected_code_remains_rejected() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.rejected_cases {
        assert_eq!(case.operation, "Matter({ qb64 })");
        assert_eq!(case.input, "RAAA");
        assert_eq!(case.reference_error_category, "Error");
        let error = case
            .hard_code
            .parse::<DerivationCode>()
            .err()
            .ok_or("reference-rejected code was accepted")?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }
    Ok(())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::UnsupportedCode { .. } => "UnsupportedCode",
        _ => "Unexpected",
    }
}
