//! Exact counter fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{
    CesrError,
    counter::{Counter, CounterCode, CounterVersion},
};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    code_sizes: Vec<CodeSizeCase>,
    cases: Vec<CounterCase>,
    default_case: DefaultCase,
    count_b64_case: CountB64Case,
    stream_case: StreamCase,
    version_cases: Vec<VersionCase>,
    reference_quirks: ReferenceQuirks,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct CodeSizeCase {
    code: String,
    hard_size: usize,
    soft_size: usize,
    full_size: usize,
    lead_size: usize,
}

#[derive(Debug, Deserialize)]
struct CounterCase {
    code: String,
    count: u32,
    qb64: String,
    qb2_hex: String,
}

#[derive(Debug, Deserialize)]
struct DefaultCase {
    code: String,
    count: u32,
    qb64: String,
}

#[derive(Debug, Deserialize)]
struct CountB64Case {
    input: String,
    count: u32,
    qb64: String,
}

#[derive(Debug, Deserialize)]
struct StreamCase {
    input: String,
    consumed_characters: usize,
    parsed_qb64: String,
}

#[derive(Debug, Deserialize)]
struct VersionCase {
    version: String,
    fallback: [u8; 3],
    qb64_digits: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    qb2_constructor: Qb2ConstructorQuirk,
    permissive_version_prefix: StrictVersionQuirk,
    extra_version_component: StrictVersionQuirk,
    invalid_soft_digits: InvalidSoftDigitsQuirk,
}

#[derive(Debug, Deserialize)]
struct Qb2ConstructorQuirk {
    parsed_code: String,
    parsed_count: i32,
    reencode_error: ReferenceError,
}

#[derive(Debug, Deserialize)]
struct StrictVersionQuirk {
    input: String,
    reference_qb64_digits: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct InvalidSoftDigitsQuirk {
    input: String,
    parsed_count: u32,
    canonical_qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceError {
    category: String,
    message: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-counter/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_records_binary_limitation() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(
        fixture.sources,
        ["src/keri/core/counter.ts", "test/core/counter.test.ts"]
    );
    assert!(fixture.binary_derivation.contains("qb2 construction leaves an invalid"));
    Ok(())
}

#[test]
fn complete_reference_size_table_matches() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.code_sizes.len(), CounterCode::ALL.len());
    for case in fixture.code_sizes {
        let code = case.code.parse::<CounterCode>()?;
        let size = code.size();
        assert_eq!(size.hard_size(), case.hard_size, "hard size for {code}");
        assert_eq!(size.soft_size(), case.soft_size, "soft size for {code}");
        assert_eq!(size.full_size(), case.full_size, "full size for {code}");
        assert_eq!(size.lead_size(), case.lead_size, "lead size for {code}");
    }
    Ok(())
}

#[test]
fn every_reference_counter_matches_in_both_domains() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.cases.len(), CounterCode::ALL.len());
    for case in fixture.cases {
        let code = case.code.parse::<CounterCode>()?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let counter = Counter::new(code, case.count)?;
        assert_eq!(counter.qb64()?, case.qb64, "qb64 mismatch for {code}");
        assert_eq!(counter.qb2()?, qb2, "qb2 mismatch for {code}");
        assert_eq!(Counter::from_qb64(&case.qb64)?, counter);
        assert_eq!(Counter::from_qb2(&qb2)?, counter);
    }
    Ok(())
}

#[test]
fn reference_construction_and_stream_capabilities_match() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let default = fixture.default_case;
    let default_code = default.code.parse::<CounterCode>()?;
    let counter = Counter::one(default_code)?;
    assert_eq!(counter.count(), default.count);
    assert_eq!(counter.qb64()?, default.qb64);

    let count_b64 = fixture.count_b64_case;
    let decoded = Counter::from_count_b64(default_code, &count_b64.input)?;
    assert_eq!(decoded.count(), count_b64.count);
    assert_eq!(decoded.qb64()?, count_b64.qb64);

    let stream = fixture.stream_case;
    let parsed = Counter::parse_qb64(&stream.input)?;
    assert_eq!(parsed.consumed(), stream.consumed_characters);
    assert_eq!(parsed.counter().qb64()?, stream.parsed_qb64);
    assert!(matches!(
        Counter::from_qb64(&stream.input),
        Err(CesrError::TrailingMaterial { .. })
    ));
    Ok(())
}

#[test]
fn every_reference_semantic_version_form_matches() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.version_cases {
        let [major, minor, patch] = case.fallback;
        let fallback = CounterVersion::new(major, minor, patch)?;
        let version = CounterVersion::parse_with_fallback(&case.version, fallback)?;
        assert_eq!(version.qb64_digits()?, case.qb64_digits);
        let protocol_counter = Counter::protocol_stack(version)?;
        assert_eq!(protocol_counter.count_b64()?, case.qb64_digits);
        assert_eq!(protocol_counter.protocol_version()?, Some(version));
    }
    Ok(())
}

#[test]
fn permissive_or_unfinished_reference_paths_are_strictly_diverged() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    let qb2 = quirks.qb2_constructor;
    assert!(qb2.parsed_code.is_empty());
    assert_eq!(qb2.parsed_count, -1);
    assert_eq!(qb2.reencode_error.category, "TypeError");
    assert!(!qb2.reencode_error.message.is_empty());
    let valid = Counter::new(CounterCode::CONTROLLER_INDEXED_SIGNATURES, 5)?;
    assert_eq!(Counter::from_qb2(&valid.qb2()?)?, valid);

    for case in [quirks.permissive_version_prefix, quirks.extra_version_component] {
        assert!(!case.reference_qb64_digits.is_empty());
        let error = case
            .input
            .parse::<CounterVersion>()
            .err()
            .ok_or("strict semantic-version case was accepted")?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }

    let soft = quirks.invalid_soft_digits;
    assert_eq!(soft.parsed_count, 0);
    assert_eq!(soft.canonical_qb64, "-AAA");
    let error = Counter::from_qb64(&soft.input)
        .err()
        .ok_or("invalid soft-count digits were accepted")?;
    assert_eq!(error_category(&error), soft.rust_error_category);
    Ok(())
}

#[test]
fn reference_rejections_map_to_stable_rust_failures() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.rejected_cases {
        assert_eq!(case.reference_error_category, "Error");
        assert!(!case.reference_error_message.is_empty());
        if case.name == "negative_count" {
            assert_eq!(case.rust_error_category, "Unrepresentable");
            continue;
        }
        let error = rejected_case_error(&case.name)?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }
    Ok(())
}

fn rejected_case_error(name: &str) -> Result<CesrError, Box<dyn Error>> {
    let result = match name {
        "empty_qb64" => Counter::from_qb64(""),
        "unsupported_selector" => Counter::from_qb64("AAAA"),
        "reserved_code" => Counter::from_qb64("-MAA"),
        "truncated_qb64" => Counter::from_qb64("-AA"),
        "short_count_too_large" => Counter::new(CounterCode::CONTROLLER_INDEXED_SIGNATURES, 4_096),
        "big_count_too_large" => Counter::new(CounterCode::BIG_ATTACHED_MATERIAL_QUADLETS, 1_073_741_824),
        "version_component_too_large" => return semantic_version_error("64.0.0"),
        "negative_version_component" => return semantic_version_error("-1.0.0"),
        _ => return Err(format!("unknown rejected fixture case {name}").into()),
    };
    result
        .err()
        .ok_or_else(|| format!("rejected fixture case {name} was accepted").into())
}

fn semantic_version_error(input: &str) -> Result<CesrError, Box<dyn Error>> {
    input
        .parse::<CounterVersion>()
        .err()
        .ok_or_else(|| format!("rejected semantic version {input} was accepted").into())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::EmptyInput { .. } => "EmptyInput",
        CesrError::UnsupportedCode { .. } => "UnsupportedCode",
        CesrError::Truncated { .. } => "Truncated",
        CesrError::CounterOutOfRange { .. } => "CounterOutOfRange",
        CesrError::InvalidSemanticVersion { .. } => "InvalidSemanticVersion",
        CesrError::SemanticVersionOutOfRange { .. } => "SemanticVersionOutOfRange",
        CesrError::InvalidBase64Character { .. } => "InvalidBase64Character",
        _ => "Unexpected",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex input has odd length".into());
    }
    input
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let high = pair.first().copied().ok_or("missing high hex digit")?;
            let low = pair.get(1).copied().ok_or("missing low hex digit")?;
            Ok((hex_value(high)? << 4) | hex_value(low)?)
        })
        .collect()
}

fn hex_value(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err("invalid hex digit".into()),
    }
}
