//! Exact X25519 decrypter fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use serde::Deserialize;
use signify_crypto::{
    CryptoError,
    cipher::{Ciphertext, CiphertextKind, Decrypter, X25519_PRIVATE_KEY_SIZE},
    salt::SecurityTier,
    signer::Signer,
    verifier::KeyTransferability,
};

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    algorithm_dependencies: String,
    secret_fixture_policy: String,
    conversion: Conversion,
    stored_reference_ciphertexts: Vec<StoredCiphertext>,
    rust_ciphertexts_opened_by_reference_decrypter: Vec<OpenedRustCiphertext>,
    rejected_cases: Vec<RejectedCase>,
    reference_quirks: ReferenceQuirks,
}

#[derive(Debug, Deserialize)]
struct Conversion {
    crypt_seed_hex: String,
    crypt_signer_qb64: String,
    x25519_private_raw_hex: String,
    decrypter_code: String,
    decrypter_qb64: String,
    from_seed_param_qb64: String,
    from_seed_param_matches_raw: bool,
}

#[derive(Debug, Deserialize)]
struct StoredCiphertext {
    name: String,
    qb64: String,
    code: String,
    raw_hex: String,
    decrypted_qb64: String,
    decrypted_code: String,
    transferable_verfer_code: Option<String>,
    non_transferable_verfer_code: Option<String>,
    ser_and_cipher_paths_agree: Option<bool>,
    expected_seed_qb64: Option<String>,
    expected_salt_qb64: Option<String>,
}

#[derive(Debug, Deserialize)]
struct OpenedRustCiphertext {
    name: String,
    qb64: String,
    decrypted_qb64: String,
    decrypted_code: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    excess_raw_truncation: ExcessRawQuirk,
    data_driven_kind_dispatch: DispatchQuirk,
    distinguishable_failure_stages: FailureStagesQuirk,
}

#[derive(Debug, Deserialize)]
struct ExcessRawQuirk {
    input_raw_hex: String,
    reference_qb64: String,
    truncated_to_reference_key: bool,
    rust_decision: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct DispatchQuirk {
    note: String,
    salt_cipher_decrypts_to_code: String,
    rust_decision: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct FailureStagesQuirk {
    note: String,
    wrong_shape_cipher_code: String,
    wrong_shape_error: RejectedCase,
    rust_decision: String,
}

fn fixture() -> Result<Fixture, Box<dyn Error>> {
    Ok(serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/crypto-decrypter/v1.json"
    )))?)
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("odd-length hexadecimal fixture field".into());
    }
    (0..input.len())
        .step_by(2)
        .map(|index| {
            input
                .get(index..index + 2)
                .ok_or_else(|| Box::<dyn Error>::from("hexadecimal fixture slice out of range"))
                .and_then(|pair| u8::from_str_radix(pair, 16).map_err(Into::into))
        })
        .collect()
}

#[test]
fn fixture_metadata_matches_the_pinned_reference() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert!(!fixture.generated_on.is_empty());
    assert!(
        fixture
            .sources
            .iter()
            .any(|source| source == "src/keri/core/decrypter.ts")
    );
    assert!(
        fixture
            .algorithm_dependencies
            .contains("crypto_sign_ed25519_sk_to_curve25519")
    );
    assert!(
        fixture
            .secret_fixture_policy
            .contains("never be used as production secrets")
    );
    Ok(())
}

#[test]
fn seed_conversion_and_construction_paths_are_byte_exact() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let conversion = &fixture.conversion;
    assert_eq!(conversion.decrypter_code, "O");
    assert!(conversion.from_seed_param_matches_raw);
    assert_eq!(conversion.from_seed_param_qb64, conversion.decrypter_qb64);

    let seed = decode_hex(&conversion.crypt_seed_hex)?;
    let signer = Signer::from_seed(&seed, KeyTransferability::Transferable)?;
    assert_eq!(
        signer_seed_qb64(&seed)?,
        conversion.crypt_signer_qb64,
        "fixture seed does not requalify"
    );

    let derived = Decrypter::from_signer(&signer);
    assert_eq!(derived.expose_qb64()?.as_str(), conversion.decrypter_qb64);

    let private_raw = decode_hex(&conversion.x25519_private_raw_hex)?;
    assert_eq!(private_raw.len(), X25519_PRIVATE_KEY_SIZE);
    let from_raw = Decrypter::from_raw(&private_raw)?;
    assert_eq!(from_raw.expose_qb64()?.as_str(), conversion.decrypter_qb64);
    assert_eq!(
        Decrypter::from_qb64(&conversion.decrypter_qb64)?.expose_qb2()?,
        derived.expose_qb2()?
    );
    Ok(())
}

fn signer_seed_qb64(seed: &[u8]) -> Result<String, CryptoError> {
    let signer = Signer::from_seed(seed, KeyTransferability::Transferable)?;
    // The qualified seed itself is deterministic public fixture material here.
    let verifier_check = signer.verifier().qb64()?;
    assert!(!verifier_check.is_empty());
    let requalified =
        signify_cesr::matter::QualifiedMaterial::new(signify_cesr::code::DerivationCode::ED25519_SEED, seed)?;
    Ok(requalified.qb64()?)
}

#[test]
fn stored_reference_ciphertexts_decrypt_to_exact_secrets() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let decrypter = Decrypter::from_qb64(&fixture.conversion.decrypter_qb64)?;

    for stored in &fixture.stored_reference_ciphertexts {
        let ciphertext = Ciphertext::from_qb64(&stored.qb64)?;
        assert_eq!(ciphertext.code().as_str(), stored.code, "case {}", stored.name);
        assert_eq!(decode_hex(&stored.raw_hex)?, ciphertext.raw(), "case {}", stored.name);

        if ciphertext.kind() == CiphertextKind::QualifiedSeed {
            {
                assert_eq!(stored.decrypted_code, "A", "case {}", stored.name);
                let expected = stored
                    .expected_seed_qb64
                    .as_deref()
                    .ok_or("seed case missing expected_seed_qb64")?;
                assert_eq!(stored.decrypted_qb64, expected, "case {}", stored.name);
                assert_eq!(stored.ser_and_cipher_paths_agree, Some(true));

                let transferable = decrypter.decrypt_seed(&ciphertext, KeyTransferability::Transferable)?;
                assert_eq!(
                    Some(transferable.verifier().code().as_str().to_owned()),
                    stored.transferable_verfer_code,
                    "case {}",
                    stored.name
                );
                let expected_signer = Signer::from_qb64(expected, KeyTransferability::Transferable)?;
                assert_eq!(
                    transferable.verifier().qb64()?,
                    expected_signer.verifier().qb64()?,
                    "case {}",
                    stored.name
                );

                let non_transferable = decrypter.decrypt_seed(&ciphertext, KeyTransferability::NonTransferable)?;
                assert_eq!(
                    Some(non_transferable.verifier().code().as_str().to_owned()),
                    stored.non_transferable_verfer_code,
                    "case {}",
                    stored.name
                );
            }
        } else {
            assert_eq!(stored.decrypted_code, "0A", "case {}", stored.name);
            let expected = stored
                .expected_salt_qb64
                .as_deref()
                .ok_or("salt case missing expected_salt_qb64")?;
            assert_eq!(stored.decrypted_qb64, expected, "case {}", stored.name);

            let salt = decrypter.decrypt_salt(&ciphertext, SecurityTier::Low)?;
            assert_eq!(salt.expose_qb64()?.as_str(), expected, "case {}", stored.name);
        }
    }
    Ok(())
}

#[test]
fn reference_decrypter_opened_rust_ciphertexts() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let decrypter = Decrypter::from_qb64(&fixture.conversion.decrypter_qb64)?;

    for case in &fixture.rust_ciphertexts_opened_by_reference_decrypter {
        let ciphertext = Ciphertext::from_qb64(&case.qb64)?;
        if ciphertext.kind() == CiphertextKind::QualifiedSeed {
            assert_eq!(case.decrypted_code, "A", "case {}", case.name);
            let recovered = decrypter.decrypt_seed(&ciphertext, KeyTransferability::Transferable)?;
            let expected = Signer::from_qb64(&case.decrypted_qb64, KeyTransferability::Transferable)?;
            assert_eq!(
                recovered.verifier().qb64()?,
                expected.verifier().qb64()?,
                "case {}",
                case.name
            );
        } else {
            assert_eq!(case.decrypted_code, "0A", "case {}", case.name);
            let recovered = decrypter.decrypt_salt(&ciphertext, SecurityTier::Low)?;
            assert_eq!(
                recovered.expose_qb64()?.as_str(),
                case.decrypted_qb64,
                "case {}",
                case.name
            );
        }
    }
    Ok(())
}

#[test]
fn reference_rejections_map_to_stable_rust_error_categories() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let decrypter = Decrypter::from_qb64(&fixture.conversion.decrypter_qb64)?;
    let private_raw = decode_hex(&fixture.conversion.x25519_private_raw_hex)?;

    for case in &fixture.rejected_cases {
        assert!(!case.reference_error_category.is_empty());
        assert!(!case.reference_error_message.is_empty());
        match case.name.as_str() {
            "empty_decrypter" => {
                assert_eq!(case.rust_error_category, "Cesr");
                assert!(matches!(Decrypter::from_raw(&[]), Err(CryptoError::Cesr { .. })));
                assert!(matches!(Decrypter::from_qb64(""), Err(CryptoError::Cesr { .. })));
            }
            "unsupported_decrypter_code" => {
                assert_eq!(case.rust_error_category, "InvalidDecrypterCode");
                let seed_material = signify_cesr::matter::QualifiedMaterial::new(
                    signify_cesr::code::DerivationCode::ED25519_SEED,
                    &private_raw,
                )?;
                assert!(matches!(
                    Decrypter::from_qb64(&seed_material.qb64()?),
                    Err(CryptoError::InvalidDecrypterCode { code: "A" })
                ));
            }
            "salt_material_as_seed_parameter" => {
                assert_eq!(case.rust_error_category, "InvalidSigningCode");
                // Rust's from_signer consumes an already validated Signer, so this state is a
                // Signer construction failure rather than a decrypter failure.
                let salt_qb64 = fixture
                    .stored_reference_ciphertexts
                    .iter()
                    .find_map(|stored| stored.expected_salt_qb64.clone())
                    .ok_or("fixture lacks a salt qb64")?;
                assert!(matches!(
                    Signer::from_qb64(&salt_qb64, KeyTransferability::Transferable),
                    Err(CryptoError::InvalidSigningCode { code: "0A" })
                ));
            }
            "decrypt_without_input" => {
                assert_eq!(case.rust_error_category, "UnrepresentableInRust");
                // `decrypt_seed`/`decrypt_salt` require a `&Ciphertext`; there is no nullable
                // input to reject at runtime.
            }
            "tampered_seed_ciphertext" => {
                assert_eq!(case.rust_error_category, "DecryptionFailed");
                let stored = fixture
                    .stored_reference_ciphertexts
                    .first()
                    .ok_or("fixture lacks stored ciphertexts")?;
                let mut tampered = decode_hex(&stored.raw_hex)?;
                if let Some(byte) = tampered.first_mut() {
                    *byte ^= 0x01;
                }
                let ciphertext = Ciphertext::from_raw(CiphertextKind::QualifiedSeed, &tampered)?;
                assert!(matches!(
                    decrypter.decrypt_seed(&ciphertext, KeyTransferability::Transferable),
                    Err(CryptoError::DecryptionFailed { .. })
                ));
            }
            other => return Err(format!("unmapped rejected case {other}").into()),
        }
    }
    Ok(())
}

#[test]
fn reference_quirks_are_pinned_and_safely_diverged() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let quirks = &fixture.reference_quirks;
    let decrypter = Decrypter::from_qb64(&fixture.conversion.decrypter_qb64)?;

    // Excess raw bytes: reference truncates to the same key; Rust rejects trailing material.
    let excess = &quirks.excess_raw_truncation;
    assert!(excess.truncated_to_reference_key);
    assert_eq!(excess.reference_qb64, fixture.conversion.decrypter_qb64);
    assert_eq!(excess.rust_error_category, "Cesr");
    assert!(!excess.rust_decision.is_empty());
    let excess_raw = decode_hex(&excess.input_raw_hex)?;
    assert_eq!(excess_raw.len(), X25519_PRIVATE_KEY_SIZE + 1);
    assert!(matches!(
        Decrypter::from_raw(&excess_raw),
        Err(CryptoError::Cesr { .. })
    ));

    // Data-driven dispatch: Rust states the expected kind and rejects mismatches before opening.
    let dispatch = &quirks.data_driven_kind_dispatch;
    assert_eq!(dispatch.salt_cipher_decrypts_to_code, "0A");
    assert_eq!(dispatch.rust_error_category, "CiphertextKindMismatch");
    assert!(!dispatch.note.is_empty());
    assert!(!dispatch.rust_decision.is_empty());
    let salt_stored = fixture
        .stored_reference_ciphertexts
        .iter()
        .find(|stored| stored.expected_salt_qb64.is_some())
        .ok_or("fixture lacks a stored salt cipher")?;
    let salt_cipher = Ciphertext::from_qb64(&salt_stored.qb64)?;
    assert!(matches!(
        decrypter.decrypt_seed(&salt_cipher, KeyTransferability::Transferable),
        Err(CryptoError::CiphertextKindMismatch {
            expected: "P",
            actual: "1AAH",
        })
    ));

    // Distinguishable failure stages upstream collapse into one Rust error category.
    let stages = &quirks.distinguishable_failure_stages;
    assert_eq!(stages.wrong_shape_cipher_code, "P");
    assert!(!stages.note.is_empty());
    assert!(!stages.rust_decision.is_empty());
    assert_eq!(stages.wrong_shape_error.rust_error_category, "DecryptionFailed");
    assert_ne!(
        stages.wrong_shape_error.reference_error_message,
        fixture
            .rejected_cases
            .iter()
            .find(|case| case.name == "tampered_seed_ciphertext")
            .map(|case| case.reference_error_message.clone())
            .unwrap_or_default(),
        "the reference distinguishes failure stages; Rust deliberately does not"
    );
    Ok(())
}
