//! Exact digest fixtures generated by the pinned TypeScript reference.

#![cfg(feature = "crypto")]

use std::error::Error;

use keri_cesr::crypto::{
    CryptoError,
    digest::{DIGEST_RAW_SIZE, Digest, DigestAlgorithm},
};
use keri_cesr::{CesrError, code::DerivationCode};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    algorithm_dependency: String,
    binary_derivation: String,
    cases: Vec<DigestCase>,
    rejected_cases: Vec<RejectedCase>,
    reference_quirks: ReferenceQuirks,
}

#[derive(Debug, Deserialize)]
struct DigestCase {
    name: String,
    serialization_hex: String,
    code: String,
    raw_hex: String,
    qb64: String,
    qb64_bytes_hex: String,
    qb2_hex: String,
    qb64_round_trip: String,
    verifies_serialization: bool,
    verifies_changed_serialization: bool,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    compare_identical_instance: CompareQuirk,
    compare_equal_copy: CompareQuirk,
    compare_equal_qb64_bytes: CompareQuirk,
    compare_different_same_algorithm: SameAlgorithmCompareQuirk,
    excess_raw_truncation: ExcessRawQuirk,
    invalid_raw_falls_back_to_serialization: FallbackQuirk,
    encoded_code_is_not_validated: EncodedCodeQuirk,
}

#[derive(Debug, Deserialize)]
struct CompareQuirk {
    reference_result: bool,
    rust_result: bool,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct SameAlgorithmCompareQuirk {
    reference_result: bool,
    rust_result: bool,
}

#[derive(Debug, Deserialize)]
struct ExcessRawQuirk {
    input_raw_hex: String,
    retained_raw_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct FallbackQuirk {
    invalid_raw_length: usize,
    serialization_hex: String,
    derived_qb64: String,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct EncodedCodeQuirk {
    unsupported_digest_code: String,
    unsupported_digest_qb64: String,
    unsupported_digest_verifies_with_blake3: bool,
    non_digest_code: String,
    non_digest_qb64: String,
    non_digest_verifies_with_blake3: bool,
    rust_unsupported_error_category: String,
    rust_invalid_error_category: String,
    rust_decision: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/crypto-digest/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-11");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/diger.ts",
            "src/keri/core/matter.ts",
            "test/core/diger.test.ts",
        ]
    );
    assert_eq!(fixture.algorithm_dependency, "@noble/hashes 1.8.0 blake3 with dkLen 32");
    assert!(fixture.binary_derivation.contains("Matter._bexfil"));
    Ok(())
}

#[test]
fn successful_reference_cases_match_exact_outputs() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        let serialization = decode_hex(&case.serialization_hex)?;
        let raw = decode_hex(&case.raw_hex)?;
        let qb64_bytes = decode_hex(&case.qb64_bytes_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let digest = Digest::derive(DigestAlgorithm::Blake3_256, &serialization);

        assert_eq!(case.code, "E", "code mismatch for {}", case.name);
        assert_eq!(digest.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(digest.raw().as_slice(), raw, "raw mismatch for {}", case.name);
        assert_eq!(digest.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(
            digest.qb64_bytes()?,
            qb64_bytes,
            "qb64 bytes mismatch for {}",
            case.name
        );
        assert_eq!(digest.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert_eq!(
            case.qb64_round_trip, case.qb64,
            "reference round trip mismatch for {}",
            case.name
        );
        assert_eq!(
            digest.verify(&serialization),
            case.verifies_serialization,
            "verify mismatch for {}",
            case.name
        );

        let mut changed = serialization.clone();
        changed.push(0xff);
        assert_eq!(
            digest.verify(&changed),
            case.verifies_changed_serialization,
            "changed verification mismatch for {}",
            case.name
        );
        assert_eq!(Digest::from_raw(DigestAlgorithm::Blake3_256, &raw)?, digest);
        assert_eq!(Digest::from_qb64(&case.qb64)?, digest);
        assert_eq!(Digest::from_qb64_bytes(&qb64_bytes)?, digest);
        assert_eq!(Digest::from_qb2(&qb2)?, digest);
    }
    Ok(())
}

#[test]
fn reference_rejections_map_to_typed_or_unrepresentable_failures() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let first_case = fixture.cases.first().ok_or("digest fixture has no successful case")?;
    for case in &fixture.rejected_cases {
        assert_ne!(case.reference_error_category, "");
        assert_ne!(case.reference_error_message, "");
        let category = match case.name.as_str() {
            "missing_material_without_serialization" => "Unrepresentable",
            "short_raw_without_serialization" => crypto_error_category(
                &Digest::from_raw(DigestAlgorithm::Blake3_256, &[0_u8; DIGEST_RAW_SIZE - 1])
                    .err()
                    .ok_or("short raw digest was accepted")?,
            ),
            "unsupported_sha3_raw" => crypto_error_category(
                &DigestAlgorithm::try_from(DerivationCode::SHA3_256)
                    .err()
                    .ok_or("SHA3-256 digest code was accepted")?,
            ),
            "qb2_constructor" => {
                let qb2 = decode_hex(&first_case.qb2_hex)?;
                assert_eq!(Digest::from_qb2(&qb2)?.qb64()?, first_case.qb64);
                "ReferenceUnsupported"
            }
            "compare_without_other_digest" => "MissingComparisonDigest",
            _ => return Err(format!("unknown rejected fixture case {}", case.name).into()),
        };
        assert_eq!(
            category, case.rust_error_category,
            "category mismatch for {}",
            case.name
        );
    }
    Ok(())
}

#[test]
fn defective_reference_quirks_are_strictly_diverged() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    let serialization = b"abcdefghijklmnopqrstuvwxyz0123456789";
    let digest = Digest::derive(DigestAlgorithm::Blake3_256, serialization);
    for quirk in [
        quirks.compare_identical_instance,
        quirks.compare_equal_copy,
        quirks.compare_equal_qb64_bytes,
    ] {
        assert!(!quirk.reference_result);
        assert!(quirk.rust_result);
        assert_ne!(quirk.rust_decision, "");
        assert_eq!(digest.compare(serialization, &digest), quirk.rust_result);
    }
    assert!(!quirks.compare_different_same_algorithm.reference_result);
    assert!(!quirks.compare_different_same_algorithm.rust_result);
    let different = Digest::derive(DigestAlgorithm::Blake3_256, b"different");
    assert!(!digest.compare(serialization, &different));

    let excess = quirks.excess_raw_truncation;
    let excess_raw = decode_hex(&excess.input_raw_hex)?;
    assert_eq!(decode_hex(&excess.retained_raw_hex)?.len(), DIGEST_RAW_SIZE);
    assert_eq!(excess.qb64, "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    let error = Digest::from_raw(DigestAlgorithm::Blake3_256, &excess_raw)
        .err()
        .ok_or("excess raw digest was silently truncated")?;
    assert_eq!(crypto_error_category(&error), excess.rust_error_category);

    let fallback = quirks.invalid_raw_falls_back_to_serialization;
    assert_eq!(fallback.invalid_raw_length, DIGEST_RAW_SIZE - 1);
    assert_ne!(fallback.rust_decision, "");
    let fallback_serialization = decode_hex(&fallback.serialization_hex)?;
    assert_eq!(
        Digest::derive(DigestAlgorithm::Blake3_256, &fallback_serialization).qb64()?,
        fallback.derived_qb64
    );
    assert!(Digest::from_raw(DigestAlgorithm::Blake3_256, &[0_u8; DIGEST_RAW_SIZE - 1]).is_err());

    let encoded = quirks.encoded_code_is_not_validated;
    assert_eq!(encoded.unsupported_digest_code, "H");
    assert!(encoded.unsupported_digest_verifies_with_blake3);
    assert_eq!(encoded.non_digest_code, "D");
    assert!(encoded.non_digest_verifies_with_blake3);
    assert_ne!(encoded.rust_decision, "");
    let unsupported = Digest::from_qb64(&encoded.unsupported_digest_qb64)
        .err()
        .ok_or("encoded unsupported digest algorithm was accepted")?;
    assert_eq!(
        crypto_error_category(&unsupported),
        encoded.rust_unsupported_error_category
    );
    let invalid = Digest::from_qb64(&encoded.non_digest_qb64)
        .err()
        .ok_or("encoded non-digest code was accepted")?;
    assert_eq!(crypto_error_category(&invalid), encoded.rust_invalid_error_category);
    Ok(())
}

fn crypto_error_category(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::Cesr { source } => match source.as_ref() {
            CesrError::Truncated { .. } => "Truncated",
            CesrError::TrailingMaterial { .. } => "TrailingMaterial",
            _ => "Cesr",
        },
        CryptoError::InvalidDigestCode { .. } => "InvalidDigestCode",
        CryptoError::UnsupportedDigestAlgorithm { .. } => "UnsupportedDigestAlgorithm",
        _ => "Other",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex fixture has odd length".into());
    }
    input
        .as_bytes()
        .as_chunks::<2>()
        .0
        .iter()
        .map(|[high, low]| Ok((decode_nibble(*high)? << 4) | decode_nibble(*low)?))
        .collect()
}

fn decode_nibble(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err(format!("invalid hex byte 0x{byte:02x}").into()),
    }
}
