//! Exact indexed-material fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{
    CesrError,
    indexer::{IndexedMaterial, IndexerCode},
};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    reference_quirks: ReferenceQuirks,
    code_sizes: Vec<CodeSizeCase>,
    fixed_cases: Vec<FixedCase>,
    stream_case: StreamCase,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    raw_size_helper: RawSizeHelperQuirk,
    omitted_ecdsa_r1_big_other_index: OmittedOtherIndexQuirk,
}

#[derive(Debug, Deserialize)]
struct RawSizeHelperQuirk {
    code: String,
    reference_reported: usize,
    constructor_required: usize,
}

#[derive(Debug, Deserialize)]
struct OmittedOtherIndexQuirk {
    code: String,
    index: u32,
    raw_hex: String,
    constructed_other_index: Option<u32>,
    reference_qb64: String,
    parsed_other_index: u32,
    explicit_safe_other_index: u32,
    explicit_safe_qb64: String,
}

#[derive(Debug, Deserialize)]
struct CodeSizeCase {
    code: String,
    hard_size: usize,
    soft_size: usize,
    other_index_size: usize,
    full_size: Option<usize>,
    lead_size: usize,
}

#[derive(Debug, Deserialize)]
struct FixedCase {
    code: String,
    raw_hex: String,
    index: u32,
    other_index: Option<u32>,
    qb64: String,
    qb2_hex: String,
}

#[derive(Debug, Deserialize)]
struct StreamCase {
    input: String,
    consumed_characters: usize,
    parsed_qb64: String,
    raw_input_hex: String,
    consumed_raw_bytes: usize,
    raw_parsed_qb64: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-indexer/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_records_binary_limitation() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(
        fixture.sources,
        ["src/keri/core/indexer.ts", "test/core/indexer.test.ts"]
    );
    assert!(fixture.binary_derivation.contains("_bexfil is unsupported"));
    Ok(())
}

#[test]
fn complete_reference_size_table_matches() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.code_sizes.len(), IndexerCode::ALL.len());
    for case in fixture.code_sizes {
        let code = case.code.parse::<IndexerCode>()?;
        let size = code.size();
        assert_eq!(size.hard_size(), case.hard_size, "hard size for {code}");
        assert_eq!(size.soft_size(), case.soft_size, "soft size for {code}");
        assert_eq!(
            size.other_index_size(),
            case.other_index_size,
            "other-index size for {code}"
        );
        assert_eq!(size.full_size(), case.full_size, "full size for {code}");
        assert_eq!(size.lead_size(), case.lead_size, "lead size for {code}");
    }
    Ok(())
}

#[test]
fn unsafe_reference_index_defaults_are_explicitly_diverged() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    let raw_size = quirks.raw_size_helper;
    assert_eq!(raw_size.code, "A");
    assert_eq!(raw_size.reference_reported, 86);
    assert_eq!(raw_size.constructor_required, 64);
    assert_eq!(IndexerCode::ED25519.size().raw_size(), Some(64));

    let case = quirks.omitted_ecdsa_r1_big_other_index;
    let code = case.code.parse::<IndexerCode>()?;
    let raw = decode_hex(&case.raw_hex)?;
    assert_eq!(case.constructed_other_index, None);
    assert_eq!(case.parsed_other_index, 0);
    assert_eq!(case.explicit_safe_other_index, case.index);
    let material = IndexedMaterial::new(code, case.index, None, &raw)?;
    assert_eq!(material.other_index(), Some(case.index));
    assert_eq!(material.qb64()?, case.explicit_safe_qb64);
    assert_ne!(material.qb64()?, case.reference_qb64);
    let unsafe_reference_value = IndexedMaterial::from_qb64(&case.reference_qb64)?;
    assert_eq!(unsafe_reference_value.other_index(), Some(0));
    Ok(())
}

#[test]
fn every_fixed_reference_case_matches_in_both_domains() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let fixed_count = IndexerCode::ALL
        .iter()
        .filter(|code| code.size().raw_size().is_some())
        .count();
    assert_eq!(fixture.fixed_cases.len(), fixed_count);

    for case in fixture.fixed_cases {
        let code = case.code.parse::<IndexerCode>()?;
        let raw = decode_hex(&case.raw_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let material = IndexedMaterial::new(code, case.index, case.other_index, &raw)?;
        assert_eq!(material.qb64()?, case.qb64, "qb64 mismatch for {code}");
        assert_eq!(material.qb2()?, qb2, "qb2 mismatch for {code}");
        assert_same(&IndexedMaterial::from_qb64(&case.qb64)?, &material);
        assert_same(&IndexedMaterial::from_qb2(&qb2)?, &material);
    }
    Ok(())
}

#[test]
fn reference_stream_prefix_behavior_maps_to_explicit_parser() -> Result<(), Box<dyn Error>> {
    let case = fixture()?.stream_case;
    let parsed = IndexedMaterial::parse_qb64(&case.input)?;
    assert_eq!(parsed.consumed(), case.consumed_characters);
    assert_eq!(parsed.material().qb64()?, case.parsed_qb64);
    assert!(matches!(
        IndexedMaterial::from_qb64(&case.input),
        Err(CesrError::TrailingMaterial { .. })
    ));

    let raw_input = decode_hex(&case.raw_input_hex)?;
    let parsed_raw = IndexedMaterial::parse_raw_prefix(IndexerCode::ED25519, 5, None, &raw_input)?;
    assert_eq!(parsed_raw.consumed(), case.consumed_raw_bytes);
    assert_eq!(parsed_raw.material().qb64()?, case.raw_parsed_qb64);
    Ok(())
}

#[test]
fn reference_rejections_map_to_stable_rust_errors() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.rejected_cases {
        assert_eq!(case.reference_error_category, "Error");
        assert!(!case.reference_error_message.is_empty());
        let error = rejected_case_error(&case.name)?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }
    Ok(())
}

fn rejected_case_error(name: &str) -> Result<CesrError, Box<dyn Error>> {
    let zero_signature = [0_u8; 64];
    let result = match name {
        "empty_qb64" => IndexedMaterial::from_qb64(""),
        "unsupported_code" => IndexedMaterial::from_qb64(&format!("G{}", "A".repeat(87))),
        "truncated_qb64" => IndexedMaterial::from_qb64("AA"),
        "short_raw" => {
            let short = zero_signature.get(..63).ok_or("missing shortened signature fixture")?;
            IndexedMaterial::new(IndexerCode::ED25519, 0, None, short)
        }
        "index_out_of_range" => IndexedMaterial::new(IndexerCode::ED25519, 64, None, &zero_signature),
        "implicit_other_mismatch" => IndexedMaterial::new(IndexerCode::ED25519, 5, Some(4), &zero_signature),
        "current_only_other_index" => IndexedMaterial::new(IndexerCode::ED25519_CURRENT, 3, Some(3), &zero_signature),
        "other_index_out_of_range" => IndexedMaterial::new(IndexerCode::ED25519_BIG, 1, Some(4_096), &zero_signature),
        "non_zero_alignment_bits" => IndexedMaterial::from_qb64(
            "AA_zVmV0k7LR8A8uTWyLqsnoByZFZIOiweD_Hj1ce5q52PcWNVRzkrHQ7w4tTGuKqcjnBiVEY4KhwN_-HTxbepm4",
        ),
        "non_zero_current_reserved_other" => {
            let raw = deterministic_raw(64, 222)?;
            let valid = IndexedMaterial::new(IndexerCode::ED25519_BIG_CURRENT, 68, None, &raw)?.qb64()?;
            let mut malformed = valid.into_bytes();
            let reserved = malformed.get_mut(5).ok_or("missing reserved other-index character")?;
            *reserved = b'B';
            IndexedMaterial::from_qb64(&String::from_utf8(malformed)?)
        }
        "variable_length_code" => {
            let code = "0z".parse::<IndexerCode>()?;
            IndexedMaterial::new(code, 0, None, &[])
        }
        _ => return Err(format!("unknown rejected fixture case {name}").into()),
    };
    result
        .err()
        .ok_or_else(|| format!("rejected fixture case {name} was accepted").into())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::EmptyInput { .. } => "EmptyInput",
        CesrError::UnsupportedCode { .. } => "UnsupportedCode",
        CesrError::Truncated { .. } => "Truncated",
        CesrError::RawSizeMismatch { .. } => "RawSizeMismatch",
        CesrError::IndexOutOfRange { .. } => "IndexOutOfRange",
        CesrError::InvalidIndexRelation { .. } => "InvalidIndexRelation",
        CesrError::NonZeroPadding { .. } => "NonZeroPadding",
        CesrError::UnsupportedVariableLength { .. } => "UnsupportedVariableLength",
        _ => "Unexpected",
    }
}

fn deterministic_raw(length: usize, salt: usize) -> Result<Vec<u8>, std::num::TryFromIntError> {
    (0..length)
        .map(|offset| u8::try_from((salt * 23 + offset * 31) % 256))
        .collect()
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut chunks = input.as_bytes().chunks_exact(2);
    let decoded = chunks
        .by_ref()
        .map(|pair| {
            let hi = pair.first().copied().ok_or("missing high hexadecimal digit")?;
            let lo = pair.get(1).copied().ok_or("missing low hexadecimal digit")?;
            let hi = hex_digit(hi).ok_or("invalid high hexadecimal digit")?;
            let lo = hex_digit(lo).ok_or("invalid low hexadecimal digit")?;
            Ok((hi << 4) | lo)
        })
        .collect::<Result<Vec<_>, Box<dyn Error>>>()?;
    if !chunks.remainder().is_empty() {
        return Err("odd hexadecimal fixture length".into());
    }
    Ok(decoded)
}

fn hex_digit(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        _ => None,
    }
}

fn assert_same(left: &IndexedMaterial, right: &IndexedMaterial) {
    assert_eq!(left.code(), right.code());
    assert_eq!(left.index(), right.index());
    assert_eq!(left.other_index(), right.other_index());
    assert_eq!(left.raw(), right.raw());
}
