//! Exact qualified-material fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{CesrError, code::DerivationCode, matter::QualifiedMaterial};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    variable_parse_divergence: String,
    fixed_cases: Vec<FixedCase>,
    variable_cases: Vec<VariableCase>,
    stream_cases: StreamCases,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct FixedCase {
    code: String,
    raw_hex: String,
    qb64: String,
    qb2_hex: String,
    transferable: bool,
    digestive: bool,
}

#[derive(Debug, Deserialize)]
struct VariableCase {
    input_code: String,
    output_code: String,
    raw_hex: String,
    size: u32,
    both: String,
    qb64: String,
    qb2_hex: String,
    reference_parse: ReferenceVariableParse,
}

#[derive(Debug, Deserialize)]
struct ReferenceVariableParse {
    code: String,
    size_is_undefined: bool,
    raw_hex: String,
    reencode_error_category: String,
}

#[derive(Debug, Deserialize)]
struct StreamCases {
    raw_prefix: RawPrefixCase,
    qb64_prefix: Qb64PrefixCase,
}

#[derive(Debug, Deserialize)]
struct RawPrefixCase {
    input_raw_hex: String,
    code: String,
    consumed_raw_bytes: usize,
    qb64: String,
}

#[derive(Debug, Deserialize)]
struct Qb64PrefixCase {
    input: String,
    consumed_characters: usize,
    parsed_qb64: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-matter/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_records_reference_gaps() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/matter.ts",
            "test/core/matter.test.ts",
            "test/core/bexter.test.ts"
        ]
    );
    assert!(fixture.binary_derivation.contains("_bexfil is unsupported"));
    assert!(fixture.variable_parse_divergence.contains("size undefined"));
    Ok(())
}

#[test]
fn every_fixed_reference_case_matches_in_both_domains() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let fixed_count = DerivationCode::ALL
        .iter()
        .filter(|code| code.size().full_size().is_some())
        .count();
    assert_eq!(fixture.fixed_cases.len(), fixed_count);

    for case in fixture.fixed_cases {
        let code = case.code.parse::<DerivationCode>()?;
        let raw = decode_hex(&case.raw_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let material = QualifiedMaterial::new(code, &raw)?;
        assert_eq!(material.qb64()?, case.qb64, "qb64 mismatch for {code}");
        assert_eq!(material.qb2()?, qb2, "qb2 mismatch for {code}");
        assert_eq!(material.is_transferable(), case.transferable);
        assert_eq!(material.is_digest(), case.digestive);
        let from_text = QualifiedMaterial::from_qb64(&case.qb64)?;
        let from_binary = QualifiedMaterial::from_qb2(&qb2)?;
        assert_same_material(&from_text, &material);
        assert_same_material(&from_binary, &material);
    }
    Ok(())
}

#[test]
fn variable_reference_construction_matches_and_rust_round_trips() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.variable_cases.len(), 14);

    for case in fixture.variable_cases {
        let input_code = case.input_code.parse::<DerivationCode>()?;
        let raw = decode_hex(&case.raw_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let material = QualifiedMaterial::new(input_code, &raw)?;
        assert_eq!(material.code().as_str(), case.output_code);
        assert_eq!(material.variable_size(), Some(case.size));
        assert_eq!(material.both()?, case.both);
        assert_eq!(material.qb64()?, case.qb64);
        assert_eq!(material.qb2()?, qb2);
        assert_eq!(case.reference_parse.code, case.output_code);
        assert!(case.reference_parse.size_is_undefined);
        assert_eq!(case.reference_parse.raw_hex, case.raw_hex);
        assert_eq!(case.reference_parse.reencode_error_category, "RangeError");
        let from_text = QualifiedMaterial::from_qb64(&case.qb64)?;
        let from_binary = QualifiedMaterial::from_qb2(&qb2)?;
        assert_same_material(&from_text, &material);
        assert_same_material(&from_binary, &material);
    }
    Ok(())
}

#[test]
fn reference_stream_prefix_behavior_maps_to_explicit_parsers() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let raw_case = fixture.stream_cases.raw_prefix;
    let input_raw = decode_hex(&raw_case.input_raw_hex)?;
    let code = raw_case.code.parse::<DerivationCode>()?;
    let parsed = QualifiedMaterial::parse_raw_prefix(code, &input_raw, raw_case.consumed_raw_bytes)?;
    assert_eq!(parsed.consumed(), raw_case.consumed_raw_bytes);
    assert_eq!(parsed.material().qb64()?, raw_case.qb64);

    let qb64_case = fixture.stream_cases.qb64_prefix;
    let parsed = QualifiedMaterial::parse_qb64(&qb64_case.input)?;
    assert_eq!(parsed.consumed(), qb64_case.consumed_characters);
    assert_eq!(parsed.material().qb64()?, qb64_case.parsed_qb64);
    Ok(())
}

#[test]
fn reference_rejections_map_to_stable_rust_errors() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.rejected_cases {
        assert_eq!(case.reference_error_category, "Error");
        assert!(!case.reference_error_message.is_empty());
        let error = rejected_case_error(&case.name)?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }
    Ok(())
}

fn rejected_case_error(name: &str) -> Result<CesrError, Box<dyn Error>> {
    let result = match name {
        "empty_qb64" => QualifiedMaterial::from_qb64(""),
        "unsupported_code" => QualifiedMaterial::from_qb64("RAAA"),
        "truncated_fixed" => QualifiedMaterial::from_qb64("A"),
        "short_fixed_raw" => QualifiedMaterial::new(DerivationCode::ED25519_SEED, &[0; 31]),
        "non_zero_code_padding" => QualifiedMaterial::from_qb64(&format!("AQ{}", "A".repeat(42))),
        "non_zero_lead_byte" => QualifiedMaterial::from_qb64("2AAABAAA"),
        _ => return Err(format!("unknown rejected fixture case {name}").into()),
    };
    result
        .err()
        .ok_or_else(|| format!("rejected fixture case {name} was accepted").into())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::EmptyInput { .. } => "EmptyInput",
        CesrError::UnsupportedCode { .. } => "UnsupportedCode",
        CesrError::Truncated { .. } => "Truncated",
        CesrError::RawSizeMismatch { .. } => "RawSizeMismatch",
        CesrError::NonZeroPadding { .. } => "NonZeroPadding",
        _ => "Unexpected",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut chunks = input.as_bytes().chunks_exact(2);
    let decoded = chunks
        .by_ref()
        .map(|pair| {
            let hi = pair.first().copied().ok_or("missing high hexadecimal digit")?;
            let lo = pair.get(1).copied().ok_or("missing low hexadecimal digit")?;
            let hi = hex_digit(hi).ok_or("invalid high hexadecimal digit")?;
            let lo = hex_digit(lo).ok_or("invalid low hexadecimal digit")?;
            Ok((hi << 4) | lo)
        })
        .collect::<Result<Vec<_>, Box<dyn Error>>>()?;
    if !chunks.remainder().is_empty() {
        return Err("odd hexadecimal fixture length".into());
    }
    Ok(decoded)
}

fn hex_digit(byte: u8) -> Option<u8> {
    match byte {
        b'0'..=b'9' => Some(byte - b'0'),
        b'a'..=b'f' => Some(byte - b'a' + 10),
        _ => None,
    }
}

fn assert_same_material(left: &QualifiedMaterial, right: &QualifiedMaterial) {
    assert_eq!(left.code(), right.code());
    assert_eq!(left.variable_size(), right.variable_size());
    assert_eq!(left.raw(), right.raw());
}
