//! Exact numeric fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{
    CesrError,
    code::DerivationCode,
    number::{CesrNumber, MAX_NUMBER_HEX_DIGITS},
};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    cases: Vec<NumberCase>,
    exact_material_cases: Vec<MaterialCase>,
    reference_quirks: ReferenceQuirks,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct NumberCase {
    name: String,
    input_kind: String,
    input: String,
    value_hex: String,
    positive: bool,
    code: String,
    raw_hex: String,
    qb64: String,
    qb2_hex: String,
}

#[derive(Debug, Deserialize)]
struct MaterialCase {
    name: String,
    value_hex: String,
    code: String,
    raw_hex: String,
    qb64: String,
    qb2_hex: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    negative_number: CoercionQuirk,
    fractional_number: CoercionQuirk,
    partial_hex: HexQuirk,
    prefixed_hex: HexQuirk,
    rounded_big_boundary: BigBoundaryQuirk,
    rounded_huge_threshold: HugeThresholdQuirk,
}

#[derive(Debug, Deserialize)]
struct CoercionQuirk {
    input: String,
    value_hex: String,
    code: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct HexQuirk {
    input: String,
    value_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct BigBoundaryQuirk {
    input_expression: String,
    exact_value_hex: String,
    decoded_value_hex: String,
    code: String,
    raw_hex: String,
    qb64: String,
    rust_code: String,
}

#[derive(Debug, Deserialize)]
struct HugeThresholdQuirk {
    input_expression: String,
    decoded_value_hex: String,
    code: String,
    raw_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-number/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_records_binary_limitation() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/number.ts",
            "src/keri/core/matter.ts",
            "src/keri/core/utils.ts",
            "test/core/number.test.ts",
        ]
    );
    assert!(fixture.binary_derivation.contains("encoded-input construction rejects"));
    Ok(())
}

#[test]
fn reference_number_construction_matches_exact_outputs() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        assert_ne!(case.name, "");
        assert!(matches!(
            case.input_kind.as_str(),
            "default" | "hex" | "number" | "number_expression"
        ));
        let number = CesrNumber::from_hex(&case.value_hex)?;
        let code = case.code.parse::<DerivationCode>()?;
        assert_eq!(number.code(), code, "code mismatch for {}", case.name);
        assert_eq!(
            number.is_positive(),
            case.positive,
            "positivity mismatch for {}",
            case.name
        );
        assert_eq!(
            number.raw()?,
            decode_hex(&case.raw_hex)?,
            "raw mismatch for {}",
            case.name
        );
        assert_eq!(number.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        let qb2 = decode_hex(&case.qb2_hex)?;
        assert_eq!(number.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert_eq!(CesrNumber::from_qb64(&case.qb64)?, number);
        assert_eq!(CesrNumber::from_qb2(&qb2)?, number);
        if case.input_kind == "hex" {
            assert_eq!(CesrNumber::from_hex(&case.input)?, number);
        }
    }
    Ok(())
}

#[test]
fn exact_matter_vectors_cover_all_numeric_boundaries() -> Result<(), Box<dyn Error>> {
    let cases = fixture()?.exact_material_cases;
    assert_eq!(cases.len(), 8);
    for case in cases {
        assert_ne!(case.name, "");
        let number = CesrNumber::from_hex(&case.value_hex)?;
        assert_eq!(number.code(), case.code.parse::<DerivationCode>()?);
        assert_eq!(number.raw()?, decode_hex(&case.raw_hex)?);
        assert_eq!(number.qb64()?, case.qb64);
        assert_eq!(number.qb2()?, decode_hex(&case.qb2_hex)?);
    }
    Ok(())
}

#[test]
fn coercion_and_partial_parse_quirks_are_strictly_diverged() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    for coercion in [quirks.negative_number, quirks.fractional_number] {
        assert_ne!(coercion.input, "");
        assert_ne!(coercion.value_hex, "");
        assert_ne!(coercion.code, "");
        assert_ne!(coercion.qb64, "");
        assert_eq!(coercion.rust_error_category, "Unrepresentable");
    }

    for case in [quirks.partial_hex, quirks.prefixed_hex] {
        assert_ne!(case.value_hex, "");
        assert_ne!(case.qb64, "");
        let error = CesrNumber::from_hex(&case.input)
            .err()
            .ok_or("partial hexadecimal input was accepted")?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }
    Ok(())
}

#[test]
fn javascript_threshold_rounding_is_not_reproduced() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    let big = quirks.rounded_big_boundary;
    assert_eq!(big.input_expression, "2 ** 64");
    assert_eq!(big.decoded_value_hex, "0");
    assert_eq!(big.code, "N");
    assert_eq!(big.raw_hex, "0000000000000000");
    assert_eq!(big.qb64, "NAAAAAAAAAAA");
    let exact = CesrNumber::from_hex(&big.exact_value_hex)?;
    assert_eq!(exact.code(), big.rust_code.parse::<DerivationCode>()?);
    assert_eq!(exact.value(), u128::from(u64::MAX) + 1);

    let huge = quirks.rounded_huge_threshold;
    assert_eq!(huge.input_expression, "2 ** 128");
    assert_eq!(huge.decoded_value_hex, "0");
    assert_eq!(huge.code, "0A");
    assert_eq!(huge.raw_hex, "00000000000000000000000000000000");
    assert_eq!(huge.qb64, "0AAAAAAAAAAAAAAAAAAAAAAA");
    let oversized = "1".repeat(MAX_NUMBER_HEX_DIGITS + 1);
    let error = CesrNumber::from_hex(&oversized)
        .err()
        .ok_or("oversized exact number was accepted")?;
    assert_eq!(error_category(&error), huge.rust_error_category);
    Ok(())
}

#[test]
fn reference_rejections_and_rust_encoded_completion_are_recorded() -> Result<(), Box<dyn Error>> {
    let one = CesrNumber::new(1);
    for case in fixture()?.rejected_cases {
        assert_eq!(case.reference_error_category, "Error");
        assert_ne!(case.reference_error_message, "");
        match case.name.as_str() {
            "invalid_hex" => {
                let error = CesrNumber::from_hex("zz")
                    .err()
                    .ok_or("invalid hexadecimal input was accepted")?;
                assert_eq!(error_category(&error), case.rust_error_category);
            }
            "positive_infinity" => assert_eq!(case.rust_error_category, "Unrepresentable"),
            "qb64_constructor" | "qb64_bytes_constructor" | "qb2_constructor" | "raw_constructor" => {
                assert_eq!(case.rust_error_category, "ReferenceUnsupported");
                assert_eq!(CesrNumber::from_qb64(&one.qb64()?)?, one);
                assert_eq!(CesrNumber::from_qb64_bytes(&one.qb64_bytes()?)?, one);
                assert_eq!(CesrNumber::from_qb2(&one.qb2()?)?, one);
            }
            _ => return Err(format!("unknown rejected fixture case {}", case.name).into()),
        }
    }
    Ok(())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::InvalidHexCharacter { .. } => "InvalidHexCharacter",
        CesrError::InputTooLarge { .. } => "InputTooLarge",
        _ => "Unexpected",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex input has odd length".into());
    }
    input
        .as_bytes()
        .as_chunks::<2>()
        .0
        .iter()
        .map(|pair| {
            let high = pair.first().copied().ok_or("missing high hex digit")?;
            let low = pair.get(1).copied().ok_or("missing low hex digit")?;
            Ok((hex_value(high)? << 4) | hex_value(low)?)
        })
        .collect()
}

fn hex_value(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err("invalid hex digit".into()),
    }
}
