//! Exact SAD-path fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{
    CesrError,
    path::{PathComponent, SadPath},
};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    access_methods_state: String,
    cases: Vec<Case>,
    boundary_cases: Vec<BoundaryCase>,
    stream_case: StreamCase,
    reference_quirks: ReferenceQuirks,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    components: Vec<String>,
    text: String,
    parsed_components: Vec<String>,
    code: String,
    size: u32,
    both: String,
    raw_hex: String,
    qb64: String,
    qb64_bytes_hex: String,
    qb2_hex: String,
}

#[derive(Debug, Deserialize)]
struct BoundaryCase {
    name: String,
    component_pattern: String,
    component_length: usize,
    text_length: usize,
    code: String,
    size: u32,
    both: String,
    raw_hex: String,
    qb64: String,
    qb2_hex: String,
    parsed_components_match: bool,
}

#[derive(Debug, Deserialize)]
struct StreamCase {
    input: String,
    declared_material_characters: usize,
    expected_components: Vec<String>,
    reference_observed_components: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    component_edges: Vec<ComponentEdge>,
    missing_leader_text: MissingLeaderText,
}

#[derive(Debug, Deserialize)]
struct ComponentEdge {
    name: String,
    components: Vec<String>,
    observed_text: String,
    observed_round_trip_components: Vec<String>,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct MissingLeaderText {
    input: String,
    qb64: String,
    path_getter_error_category: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-path/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_complete() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/pather.ts",
            "src/keri/core/bexter.ts",
            "src/keri/core/matter.ts",
            "src/keri/core/base64.ts",
            "src/keri/app/exchanging.ts",
            "test/core/pather.test.ts",
        ]
    );
    assert!(fixture.binary_derivation.contains("_bexfil is unimplemented"));
    assert!(fixture.access_methods_state.contains("marks root, strip"));
    assert_eq!(fixture.cases.len(), 6);
    assert_eq!(fixture.boundary_cases.len(), 2);
    assert_eq!(fixture.rejected_cases.len(), 5);
    Ok(())
}

#[test]
fn all_reference_paths_match_exactly_in_every_domain() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        let raw = decode_hex(&case.raw_hex)?;
        let qb64_bytes = decode_hex(&case.qb64_bytes_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let path = SadPath::from_components(&case.components)?;
        assert_eq!(path.text()?, case.text, "text mismatch for {}", case.name);
        assert_eq!(path.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(path.variable_size(), Some(case.size), "size mismatch for {}", case.name);
        assert_eq!(path.both()?, case.both, "leader mismatch for {}", case.name);
        assert_eq!(path.raw(), raw, "raw mismatch for {}", case.name);
        assert_eq!(path.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(path.qb64_bytes()?, qb64_bytes, "qb64 bytes mismatch for {}", case.name);
        assert_eq!(path.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert_eq!(component_text(&path), case.parsed_components);
        assert_eq!(SadPath::from_qb64(&case.qb64)?, path);
        assert_eq!(SadPath::from_qb2(&qb2)?, path);
    }
    Ok(())
}

#[test]
fn small_to_large_boundary_matches_complete_reference_artifacts() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.boundary_cases {
        assert_eq!(case.component_pattern.len(), 1, "invalid pattern for {}", case.name);
        let component = case.component_pattern.repeat(case.component_length);
        let raw = decode_hex(&case.raw_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let path = SadPath::from_components([component.as_str()])?;
        assert_eq!(
            path.text()?.len(),
            case.text_length,
            "text length mismatch for {}",
            case.name
        );
        assert_eq!(path.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(path.variable_size(), Some(case.size), "size mismatch for {}", case.name);
        assert_eq!(path.both()?, case.both, "leader mismatch for {}", case.name);
        assert_eq!(path.raw(), raw, "raw mismatch for {}", case.name);
        assert_eq!(path.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(path.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert!(case.parsed_components_match);
        assert_eq!(SadPath::from_qb64(&case.qb64)?, path);
        assert_eq!(SadPath::from_qb2(&qb2)?, path);
    }
    Ok(())
}

#[test]
fn stream_and_ambiguous_reference_behaviors_are_explicit_divergences() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let stream = fixture.stream_case;
    let parsed = SadPath::parse_qb64(&stream.input)?;
    assert_eq!(parsed.consumed(), stream.declared_material_characters);
    assert_eq!(component_text(parsed.value()), stream.expected_components);
    assert_ne!(stream.reference_observed_components, stream.expected_components);
    assert!(matches!(
        SadPath::from_qb64(&stream.input),
        Err(CesrError::TrailingMaterial { .. })
    ));

    for case in fixture.reference_quirks.component_edges {
        assert_ne!(case.observed_text, "");
        assert_ne!(case.qb64, "");
        match case.name.as_str() {
            "internal_identity_component" => {
                assert_eq!(case.rust_error_category, "Matched");
                assert_eq!(case.observed_round_trip_components, case.components);
                let path = SadPath::from_components(&case.components)?;
                assert_eq!(component_text(&path), case.components);
                assert_eq!(path.qb64()?, case.qb64);
            }
            "leading_identity_component" | "separator_in_component" => {
                assert_eq!(case.rust_error_category, "InvalidPathComponent");
                assert_ne!(case.observed_round_trip_components, case.components);
                assert!(matches!(
                    SadPath::from_components(&case.components),
                    Err(CesrError::InvalidPathComponent { .. })
                ));
            }
            name => return Err(format!("unknown ambiguous fixture case {name}").into()),
        }
    }

    let missing = fixture.reference_quirks.missing_leader_text;
    assert_ne!(missing.qb64, "");
    assert_eq!(missing.path_getter_error_category, "Error");
    let error = SadPath::from_text(&missing.input)
        .err()
        .ok_or("path text without a leader was accepted")?;
    assert_eq!(error_category(&error), missing.rust_error_category);
    Ok(())
}

#[test]
fn reference_rejections_and_rust_qb2_completion_are_recorded() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    for case in &fixture.rejected_cases {
        assert_ne!(case.reference_error_category, "");
        assert_ne!(case.reference_error_message, "");
        match case.name.as_str() {
            "missing_path" => assert_eq!(case.rust_error_category, "Unrepresentable"),
            "invalid_dollar_component" => assert_rejected_component("Not$Base64", case)?,
            "invalid_at_component" => assert_rejected_component("@moreso", case)?,
            "invalid_star_component" => assert_rejected_component("*again", case)?,
            "qb2_constructor" => {
                assert_eq!(case.rust_error_category, "ReferenceUnsupported");
                let source = fixture
                    .cases
                    .iter()
                    .find(|candidate| candidate.name == "exchange_embed_attachment")
                    .ok_or("missing qb2 completion source case")?;
                let path = SadPath::from_qb2(&decode_hex(&source.qb2_hex)?)?;
                assert_eq!(component_text(&path), source.components);
            }
            name => return Err(format!("unknown rejected fixture case {name}").into()),
        }
    }
    Ok(())
}

fn assert_rejected_component(input: &str, case: &RejectedCase) -> Result<(), Box<dyn Error>> {
    let error = PathComponent::parse(input)
        .err()
        .ok_or("reference-rejected path component was accepted")?;
    assert_eq!(error_category(&error), case.rust_error_category);
    Ok(())
}

fn component_text(path: &SadPath) -> Vec<String> {
    path.components()
        .iter()
        .map(|component| component.as_str().to_owned())
        .collect()
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::InvalidBase64Character { .. } => "InvalidBase64Character",
        CesrError::InvalidPath { .. } => "InvalidPath",
        CesrError::InvalidPathComponent { .. } => "InvalidPathComponent",
        _ => "Unexpected",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    let (pairs, remainder) = input.as_bytes().as_chunks::<2>();
    if !remainder.is_empty() {
        return Err("odd-length hexadecimal fixture".into());
    }
    pairs
        .iter()
        .map(|chunk| {
            let text = std::str::from_utf8(chunk)?;
            Ok(u8::from_str_radix(text, 16)?)
        })
        .collect()
}
