//! Cross-language fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{
    CesrError,
    base64::{decode_u64, decode_url_safe, encode_u64, encode_url_safe},
    bytes::{bytes_to_integer, integer_to_bytes},
};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    base64_cases: Vec<Base64Case>,
    integer_cases: Vec<IntegerCase>,
    byte_integer_cases: Vec<ByteIntegerCase>,
    rejected_cases: Vec<RejectedCase>,
    strict_rejections: Vec<StrictRejection>,
}

#[derive(Debug, Deserialize)]
struct Base64Case {
    raw: Vec<u8>,
    encoded: String,
    accepted_decodings: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct IntegerCase {
    value: String,
    minimum_width: u8,
    encoded: String,
    decoded: Option<String>,
}

#[derive(Debug, Deserialize)]
struct ByteIntegerCase {
    value: String,
    length: u8,
    encoded: Vec<u8>,
    decoded: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    operation: String,
    input: String,
    reference_error_category: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct StrictRejection {
    operation: String,
    input: String,
    reference_output: Vec<u8>,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-foundations/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.generated_on, "2026-08-03");
    Ok(())
}

#[test]
fn base64_vectors_match_exactly() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.base64_cases {
        assert_eq!(encode_url_safe(&case.raw), case.encoded);
        for accepted in case.accepted_decodings {
            assert_eq!(decode_url_safe(&accepted)?, case.raw);
        }
    }
    Ok(())
}

#[test]
fn integer_vectors_match_exactly() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.integer_cases {
        let value = case.value.parse::<u64>()?;
        assert_eq!(encode_u64(value, case.minimum_width)?, case.encoded);
        if let Some(decoded) = case.decoded {
            assert_eq!(decode_u64(&case.encoded)?.to_string(), decoded);
        }
    }
    Ok(())
}

#[test]
fn byte_integer_vectors_match_exactly() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.byte_integer_cases {
        let value = case.value.parse::<u128>()?;
        assert_eq!(integer_to_bytes(value, case.length)?, case.encoded);
        assert_eq!(bytes_to_integer(&case.encoded)?.to_string(), case.decoded);
    }
    Ok(())
}

#[test]
fn reference_rejection_and_safe_divergences_are_stable() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    for case in fixture.rejected_cases {
        assert_eq!(case.operation, "decode_u64");
        assert_eq!(case.reference_error_category, "Error");
        let error = decode_u64(&case.input).err().ok_or("fixture input was accepted")?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }
    for case in fixture.strict_rejections {
        assert_eq!(case.operation, "decode_url_safe");
        assert!(case.reference_output.len() <= 1);
        let error = decode_url_safe(&case.input)
            .err()
            .ok_or("strict rejection fixture was accepted")?;
        assert_eq!(error_category(&error), case.rust_error_category);
    }
    Ok(())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::EmptyInput { .. } => "EmptyInput",
        CesrError::InvalidLength { .. } => "InvalidLength",
        CesrError::InputTooLarge { .. } => "InputTooLarge",
        CesrError::InvalidBase64Character { .. } => "InvalidBase64Character",
        CesrError::InvalidBase64Padding { .. } => "InvalidBase64Padding",
        CesrError::NonCanonicalBase64 => "NonCanonicalBase64",
        CesrError::IntegerOverflow { .. } => "IntegerOverflow",
        CesrError::ValueDoesNotFit { .. } => "ValueDoesNotFit",
        CesrError::LengthOverflow { .. } => "LengthOverflow",
        CesrError::InvalidUtf8 { .. } => "InvalidUtf8",
        _ => "Unknown",
    }
}
