//! Exact salt and deterministic-derivation fixtures generated by the pinned TypeScript reference.

#![cfg(feature = "crypto")]

use std::error::Error;

use keri_cesr::crypto::{
    CryptoError,
    salt::{KeyDerivationProfile, MAX_DERIVATION_PATH_BYTES, Salt, SecurityTier},
    signer::Signer,
    verifier::KeyTransferability,
};
use keri_cesr::{CesrError, code::DerivationCode, matter::QualifiedMaterial};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    algorithm_dependencies: String,
    binary_derivation: String,
    secret_fixture_policy: String,
    profile_parameters: ProfileParameters,
    cases: Vec<DerivationCase>,
    rejected_cases: Vec<RejectedCase>,
    reference_quirks: ReferenceQuirks,
}

#[derive(Debug, Deserialize)]
struct ProfileParameters {
    temporary: Cost,
    low: Cost,
    med: Cost,
    high: Cost,
    parallelism: u32,
    algorithm: String,
}

#[derive(Debug, Deserialize)]
struct Cost {
    iterations: u32,
    memory_bytes: u64,
}

#[derive(Debug, Deserialize)]
struct DerivationCase {
    name: String,
    path: String,
    path_utf8_hex: String,
    tier: String,
    temporary: bool,
    transferable: bool,
    salt_code: String,
    salt_raw_hex: String,
    salt_qb64: String,
    salt_qb64_bytes_hex: String,
    salt_qb2_hex: String,
    salt_qb64_round_trip: String,
    seed_code: String,
    seed_raw_hex: String,
    seed_qb64: String,
    seed_qb64_round_trip: String,
    verifier_code: String,
    verifier_qb64: String,
    serialization_hex: String,
    signature_code: String,
    signature_raw_hex: String,
    signature_qb64: String,
    signature_qb64_round_trip: String,
    verifies_serialization: bool,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    excess_raw_truncation: ExcessRawQuirk,
    null_tier_defaults_low: NullTierQuirk,
    secret_exposure: SecretExposureQuirk,
    path_bound: PathBoundQuirk,
}

#[derive(Debug, Deserialize)]
struct ExcessRawQuirk {
    input_raw_hex: String,
    retained_raw_hex: String,
    salt_qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct NullTierQuirk {
    resulting_tier: String,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct SecretExposureQuirk {
    reference_raw_and_qb64_are_public: bool,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct PathBoundQuirk {
    reference_has_no_explicit_bound: bool,
    rust_maximum_utf8_bytes: usize,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/crypto-salt/v1.json"
    )))
}

#[test]
fn fixture_metadata_and_cost_profiles_are_pinned() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-13");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/salter.ts",
            "src/keri/core/signer.ts",
            "src/keri/core/matter.ts",
            "test/core/salter.test.ts",
        ]
    );
    assert!(fixture.algorithm_dependencies.contains("libsodium-wrappers-sumo 0.8.4"));
    assert!(fixture.algorithm_dependencies.contains("Argon2id v1.3"));
    assert!(fixture.binary_derivation.contains("qb2 constructor is unimplemented"));
    assert!(
        fixture
            .secret_fixture_policy
            .contains("never be used as production secrets")
    );
    assert_eq!(fixture.cases.len(), 5);
    assert_eq!(fixture.rejected_cases.len(), 4);

    let profiles = [
        (KeyDerivationProfile::Temporary, &fixture.profile_parameters.temporary),
        (
            KeyDerivationProfile::Standard(SecurityTier::Low),
            &fixture.profile_parameters.low,
        ),
        (
            KeyDerivationProfile::Standard(SecurityTier::Medium),
            &fixture.profile_parameters.med,
        ),
        (
            KeyDerivationProfile::Standard(SecurityTier::High),
            &fixture.profile_parameters.high,
        ),
    ];
    for (profile, expected) in profiles {
        assert_eq!(profile.iterations(), expected.iterations);
        assert_eq!(u64::from(profile.memory_kibibytes()) * 1_024, expected.memory_bytes);
    }
    assert_eq!(fixture.profile_parameters.parallelism, 1);
    assert_eq!(fixture.profile_parameters.algorithm, "Argon2id v1.3");
    Ok(())
}

#[test]
fn every_reference_derivation_and_signature_matches_exactly() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        assert!(!case.name.is_empty());
        let raw = decode_hex(&case.salt_raw_hex)?;
        let qb64_bytes = decode_hex(&case.salt_qb64_bytes_hex)?;
        let qb2 = decode_hex(&case.salt_qb2_hex)?;
        let path_bytes = decode_hex(&case.path_utf8_hex)?;
        let seed = decode_hex(&case.seed_raw_hex)?;
        let serialization = decode_hex(&case.serialization_hex)?;
        let signature_raw = decode_hex(&case.signature_raw_hex)?;
        let tier = tier(&case.tier)?;
        let transferability = transferability(case.transferable);
        let profile = if case.temporary {
            KeyDerivationProfile::Temporary
        } else {
            KeyDerivationProfile::Standard(tier)
        };

        assert_eq!(case.path.as_bytes(), path_bytes);
        let salt = Salt::from_raw(&raw, tier)?;
        assert_eq!(salt.code().as_str(), case.salt_code);
        assert_eq!(salt.expose_qb64()?.as_str(), case.salt_qb64);
        assert_eq!(salt.expose_qb64_bytes()?.as_slice(), qb64_bytes);
        assert_eq!(salt.expose_qb2()?.as_slice(), qb2);
        assert_eq!(
            Salt::from_qb64(&case.salt_qb64, tier)?.expose_qb64()?.as_str(),
            case.salt_qb64_round_trip
        );
        assert_eq!(
            Salt::from_qb64_bytes(&qb64_bytes, tier)?.expose_qb64()?.as_str(),
            case.salt_qb64
        );
        assert_eq!(Salt::from_qb2(&qb2, tier)?.expose_qb64()?.as_str(), case.salt_qb64);

        let derived = salt.derive_signer_with_profile(&case.path, transferability, profile)?;
        let expected = Signer::from_seed(&seed, transferability)?;
        assert_eq!(expected.code().as_str(), case.seed_code);
        assert_eq!(case.seed_qb64_round_trip, case.seed_qb64);
        assert_eq!(derived.verifier(), expected.verifier());
        assert_eq!(derived.verifier().code().as_str(), case.verifier_code);
        assert_eq!(derived.verifier().qb64()?, case.verifier_qb64);

        let signature = derived.sign_unindexed(&serialization)?;
        assert_eq!(signature.code().as_str(), case.signature_code);
        assert_eq!(signature.raw().as_slice(), signature_raw);
        assert_eq!(signature.qb64()?, case.signature_qb64);
        assert_eq!(case.signature_qb64_round_trip, case.signature_qb64);
        assert!(case.verifies_serialization);
        derived.verifier().verify(signature.raw(), &serialization)?;
    }
    Ok(())
}

#[test]
fn reference_rejections_map_to_typed_or_unrepresentable_rust_behavior() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let first = fixture.cases.first().ok_or("salt fixture has no cases")?;
    let raw = decode_hex(&first.salt_raw_hex)?;
    let qb2 = decode_hex(&first.salt_qb2_hex)?;
    for case in fixture.rejected_cases {
        assert!(!case.reference_error_category.is_empty());
        assert!(!case.reference_error_message.is_empty());
        let category = match case.name.as_str() {
            "short_salt" => {
                let short = raw.get(..15).ok_or("fixture salt is shorter than 15 bytes")?;
                crypto_error_category(
                    &Salt::from_raw(short, SecurityTier::Low)
                        .err()
                        .ok_or("short salt was accepted")?,
                )
            }
            "invalid_digest_code" => {
                let material = QualifiedMaterial::new(DerivationCode::BLAKE3_256, &[0_u8; 32])?;
                crypto_error_category(
                    &Salt::from_qb64(&material.qb64()?, SecurityTier::Low)
                        .err()
                        .ok_or("digest material was accepted as salt")?,
                )
            }
            "unsupported_tier" => "UnrepresentableSecurityTier",
            "qb2_constructor" => {
                let salt = Salt::from_qb2(&qb2, SecurityTier::Low)?;
                assert_eq!(salt.expose_qb64()?.as_str(), first.salt_qb64);
                "ReferenceUnsupported"
            }
            other => return Err(format!("unknown rejected salt fixture case {other}").into()),
        };
        assert_eq!(
            category, case.rust_error_category,
            "category mismatch for {}",
            case.name
        );
    }
    Ok(())
}

#[test]
fn strict_secret_and_input_behavior_pins_reference_quirks() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    let excess = quirks.excess_raw_truncation;
    let input = decode_hex(&excess.input_raw_hex)?;
    let retained = decode_hex(&excess.retained_raw_hex)?;
    let parsed = Salt::parse_raw_prefix(&input, SecurityTier::Low)?;
    assert_eq!(parsed.consumed(), retained.len());
    assert_eq!(parsed.salt().expose_qb64()?.as_str(), excess.salt_qb64);
    let error = Salt::from_raw(&input, SecurityTier::Low)
        .err()
        .ok_or("excess salt bytes were silently truncated")?;
    assert_eq!(crypto_error_category(&error), excess.rust_error_category);

    assert_eq!(quirks.null_tier_defaults_low.resulting_tier, "low");
    assert_eq!(SecurityTier::default(), SecurityTier::Low);
    assert!(quirks.null_tier_defaults_low.rust_decision.contains("non-null"));
    assert!(quirks.secret_exposure.reference_raw_and_qb64_are_public);
    assert!(quirks.secret_exposure.rust_decision.contains("zeroizing"));
    assert!(quirks.path_bound.reference_has_no_explicit_bound);
    assert_eq!(quirks.path_bound.rust_maximum_utf8_bytes, MAX_DERIVATION_PATH_BYTES);
    let oversized = "x".repeat(MAX_DERIVATION_PATH_BYTES + 1);
    let salt = Salt::from_raw(&retained, SecurityTier::Low)?;
    let path_error = salt
        .derive_signer_with_profile(
            &oversized,
            KeyTransferability::Transferable,
            KeyDerivationProfile::Temporary,
        )
        .err()
        .ok_or("oversized derivation path was accepted")?;
    assert_eq!(
        crypto_error_category(&path_error),
        quirks.path_bound.rust_error_category
    );
    Ok(())
}

fn tier(value: &str) -> Result<SecurityTier, Box<dyn Error>> {
    match value {
        "low" => Ok(SecurityTier::Low),
        "med" => Ok(SecurityTier::Medium),
        "high" => Ok(SecurityTier::High),
        other => Err(format!("unknown fixture tier {other}").into()),
    }
}

const fn transferability(value: bool) -> KeyTransferability {
    if value {
        KeyTransferability::Transferable
    } else {
        KeyTransferability::NonTransferable
    }
}

fn crypto_error_category(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::Cesr { source } => match source.as_ref() {
            CesrError::Truncated { .. } => "Truncated",
            CesrError::TrailingMaterial { .. } => "TrailingMaterial",
            _ => "Cesr",
        },
        CryptoError::InvalidSaltCode { .. } => "InvalidSaltCode",
        CryptoError::DerivationPathTooLong { .. } => "DerivationPathTooLong",
        CryptoError::KeyDerivationMemoryUnavailable { .. } => "KeyDerivationMemoryUnavailable",
        CryptoError::KeyDerivationFailed { .. } => "KeyDerivationFailed",
        _ => "OtherCryptoError",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex input has odd length".into());
    }
    let mut output = Vec::with_capacity(input.len() / 2);
    for pair in input.as_bytes().chunks_exact(2) {
        let text = std::str::from_utf8(pair)?;
        output.push(u8::from_str_radix(text, 16)?);
    }
    Ok(output)
}
