//! Fixed-width sequence fixtures generated by the pinned TypeScript reference.

use std::error::Error;

use keri_cesr::{
    CesrError,
    code::DerivationCode,
    matter::QualifiedMaterial,
    sequence::{SEQUENCE_RAW_SIZE, SequenceNumber},
};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    cases: Vec<SequenceCase>,
    exact_raw_cases: Vec<ExactRawCase>,
    reference_quirks: ReferenceQuirks,
    rejected_cases: Vec<RejectedCase>,
}

#[derive(Debug, Deserialize)]
struct SequenceCase {
    name: String,
    input_kind: String,
    input: String,
    value_hex: String,
    code: String,
    raw_hex: String,
    qb64: String,
    qb64_bytes_hex: String,
    qb2_hex: String,
    qb64_round_trip: String,
}

#[derive(Debug, Deserialize)]
struct ExactRawCase {
    name: String,
    value_hex: String,
    code: String,
    raw_hex: String,
    observed_reference_snh: String,
    qb64: String,
    qb2_hex: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    negative_number: CoercionQuirk,
    fractional_number: CoercionQuirk,
    partial_hex: CoercionQuirk,
    prefixed_hex: CoercionQuirk,
    positive_infinity: CoercionQuirk,
    excess_raw_truncation: RawTruncationQuirk,
}

#[derive(Debug, Deserialize)]
struct CoercionQuirk {
    input_kind: String,
    input: String,
    observed_snh: String,
    raw_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct RawTruncationQuirk {
    input_raw_hex: String,
    retained_raw_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/cesr-sequence/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_records_binary_derivation() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.generated_on, "2026-08-04");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/seqner.ts",
            "src/keri/core/matter.ts",
            "src/keri/core/utils.ts",
            "test/core/seqner.test.ts",
        ]
    );
    assert!(fixture.binary_derivation.contains("Matter._bexfil is unimplemented"));
    Ok(())
}

#[test]
fn upstream_sequence_cases_match_exact_outputs_and_reverse_qb64() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        assert_ne!(case.name, "");
        assert!(matches!(case.input_kind.as_str(), "default" | "hex" | "number"));
        let sequence = SequenceNumber::from_hex(&case.value_hex)?;
        assert_eq!(sequence.code(), case.code.parse::<DerivationCode>()?);
        assert_eq!(sequence.raw().as_slice(), decode_hex(&case.raw_hex)?);
        assert_eq!(sequence.qb64()?, case.qb64);
        assert_eq!(sequence.qb64_bytes()?, decode_hex(&case.qb64_bytes_hex)?);
        assert_eq!(sequence.qb2()?, decode_hex(&case.qb2_hex)?);
        assert_eq!(SequenceNumber::from_qb64(&case.qb64)?, sequence);
        assert_eq!(case.qb64_round_trip, case.qb64);
        if case.input_kind == "hex" {
            assert_eq!(SequenceNumber::from_hex(&case.input)?, sequence);
        }
    }
    Ok(())
}

#[test]
fn exact_raw_vectors_cover_the_full_fixed_width() -> Result<(), Box<dyn Error>> {
    let cases = fixture()?.exact_raw_cases;
    assert_eq!(cases.len(), 3);
    for case in cases {
        assert_ne!(case.name, "");
        assert_ne!(case.observed_reference_snh, "");
        let raw = decode_hex(&case.raw_hex)?;
        assert_eq!(raw.len(), SEQUENCE_RAW_SIZE);
        let sequence = SequenceNumber::from_hex(&case.value_hex)?;
        assert_eq!(sequence.code(), case.code.parse::<DerivationCode>()?);
        assert_eq!(sequence.raw().as_slice(), raw);
        assert_eq!(sequence.qb64()?, case.qb64);
        assert_eq!(sequence.qb2()?, decode_hex(&case.qb2_hex)?);
        assert_eq!(SequenceNumber::from_raw(&raw)?, sequence);
    }
    Ok(())
}

#[test]
fn javascript_coercion_and_partial_parse_quirks_are_not_reproduced() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    for coercion in [
        quirks.negative_number,
        quirks.fractional_number,
        quirks.positive_infinity,
    ] {
        assert_eq!(coercion.input_kind, "number");
        assert_ne!(coercion.input, "");
        assert_ne!(coercion.observed_snh, "");
        assert_eq!(decode_hex(&coercion.raw_hex)?.len(), SEQUENCE_RAW_SIZE);
        assert_ne!(coercion.qb64, "");
        assert_eq!(coercion.rust_error_category, "Unrepresentable");
    }

    for partial in [quirks.partial_hex, quirks.prefixed_hex] {
        assert_eq!(partial.input_kind, "hex");
        assert_ne!(partial.observed_snh, "");
        assert_eq!(decode_hex(&partial.raw_hex)?.len(), SEQUENCE_RAW_SIZE);
        assert_ne!(partial.qb64, "");
        let error = SequenceNumber::from_hex(&partial.input)
            .err()
            .ok_or("partial hexadecimal sequence input was accepted")?;
        assert_eq!(error_category(&error), partial.rust_error_category);
    }
    Ok(())
}

#[test]
fn reference_raw_truncation_is_an_explicit_strict_divergence() -> Result<(), Box<dyn Error>> {
    let quirk = fixture()?.reference_quirks.excess_raw_truncation;
    let input = decode_hex(&quirk.input_raw_hex)?;
    let retained = decode_hex(&quirk.retained_raw_hex)?;
    assert_eq!(input.len(), SEQUENCE_RAW_SIZE + 1);
    assert_eq!(retained.len(), SEQUENCE_RAW_SIZE);
    assert_eq!(SequenceNumber::from_raw(&retained)?.qb64()?, quirk.qb64);
    let error = SequenceNumber::from_raw(&input)
        .err()
        .ok_or("excess raw sequence input was accepted")?;
    assert_eq!(error_category(&error), quirk.rust_error_category);
    Ok(())
}

#[test]
fn reference_rejections_and_rust_qb2_completion_are_recorded() -> Result<(), Box<dyn Error>> {
    let zero = SequenceNumber::ZERO;
    for case in fixture()?.rejected_cases {
        assert_eq!(case.reference_error_category, "Error");
        assert_ne!(case.reference_error_message, "");
        match case.name.as_str() {
            "wrong_code" => {
                let material = QualifiedMaterial::new(DerivationCode::SHORT_NUMBER, &[0_u8; 2])?;
                let error = SequenceNumber::from_qb64(&material.qb64()?)
                    .err()
                    .ok_or("wrong sequence code was accepted")?;
                assert_eq!(error_category(&error), case.rust_error_category);
            }
            "short_raw" | "empty_raw" => {
                let length = if case.name == "short_raw" { 15 } else { 0 };
                let raw = vec![0_u8; length];
                let error = SequenceNumber::from_raw(&raw)
                    .err()
                    .ok_or("short sequence raw material was accepted")?;
                assert_eq!(error_category(&error), case.rust_error_category);
            }
            "qb2_constructor" => {
                assert_eq!(case.rust_error_category, "ReferenceUnsupported");
                assert_eq!(SequenceNumber::from_qb2(&zero.qb2()?)?, zero);
            }
            _ => return Err(format!("unknown rejected fixture case {}", case.name).into()),
        }
    }
    Ok(())
}

fn error_category(error: &CesrError) -> &'static str {
    match error {
        CesrError::InvalidHexCharacter { .. } => "InvalidHexCharacter",
        CesrError::InvalidSequenceCode { .. } => "InvalidSequenceCode",
        CesrError::TrailingMaterial { .. } => "TrailingMaterial",
        CesrError::Truncated { .. } => "Truncated",
        _ => "Unexpected",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex input has odd length".into());
    }
    input
        .as_bytes()
        .as_chunks::<2>()
        .0
        .iter()
        .map(|pair| {
            let high = pair.first().copied().ok_or("missing high hex digit")?;
            let low = pair.get(1).copied().ok_or("missing low hex digit")?;
            Ok((hex_value(high)? << 4) | hex_value(low)?)
        })
        .collect()
}

fn hex_value(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err(format!("invalid hex byte 0x{byte:02x}").into()),
    }
}
