//! Exact unindexed-signature fixtures generated by the pinned TypeScript reference.

#![cfg(feature = "crypto")]

use std::error::Error;

use keri_cesr::crypto::{
    CryptoError,
    signature::{SignatureAlgorithm, UnindexedSignature},
    verifier::VerificationKey,
};
use keri_cesr::{CesrError, code::DerivationCode, matter::QualifiedMaterial};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    binary_derivation: String,
    cases: Vec<SignatureCase>,
    rejected_cases: Vec<RejectedCase>,
    reference_quirks: ReferenceQuirks,
}

#[derive(Debug, Deserialize)]
struct SignatureCase {
    name: String,
    code: String,
    raw_hex: String,
    qb64: String,
    qb64_bytes_hex: String,
    qb2_hex: String,
    qb64_round_trip: String,
    verifier_qb64: Option<String>,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    excess_raw_truncation: ExcessRawQuirk,
    non_signature_code_accepted: NonSignatureCodeQuirk,
    mismatched_verifier_accepted: MismatchedVerifierQuirk,
    mutable_verifier_reassignment: MutableVerifierQuirk,
}

#[derive(Debug, Deserialize)]
struct ExcessRawQuirk {
    input_raw_hex: String,
    retained_raw_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct NonSignatureCodeQuirk {
    input_code: String,
    retained_raw_hex: String,
    qb64: String,
    rust_error_category: String,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct MismatchedVerifierQuirk {
    signature_code: String,
    verifier_code: String,
    rust_error_category: String,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct MutableVerifierQuirk {
    cleared_verifier_is_undefined: bool,
    reassigned_verifier_qb64: String,
    rust_decision: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/crypto-signature/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-12");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/cigar.ts",
            "src/keri/core/matter.ts",
            "test/core/signer.test.ts",
            "test/end/ending.test.ts",
        ]
    );
    assert!(fixture.binary_derivation.contains("Matter._bexfil"));
    Ok(())
}

#[test]
fn all_reference_signature_codes_match_in_every_domain() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        let algorithm = classification(&case.code)?;
        let raw = decode_hex(&case.raw_hex)?;
        let qb64_bytes = decode_hex(&case.qb64_bytes_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let mut signature = UnindexedSignature::from_raw(algorithm, &raw)?;

        assert_eq!(signature.algorithm(), algorithm, "algorithm mismatch for {}", case.name);
        assert_eq!(signature.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(signature.raw().as_slice(), raw, "raw mismatch for {}", case.name);
        assert_eq!(signature.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(
            signature.qb64_bytes()?,
            qb64_bytes,
            "qb64 bytes mismatch for {}",
            case.name
        );
        assert_eq!(signature.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert_eq!(case.qb64_round_trip, case.qb64);
        assert_eq!(UnindexedSignature::from_qb64(&case.qb64)?, signature);
        assert_eq!(UnindexedSignature::from_qb64_bytes(&qb64_bytes)?, signature);
        assert_eq!(UnindexedSignature::from_qb2(&qb2)?, signature);

        if let Some(verifier_qb64) = case.verifier_qb64 {
            let verifier = VerificationKey::from_qb64(&verifier_qb64)?;
            signature = signature.with_verifier(verifier.clone())?;
            assert_eq!(signature.verifier(), Some(&verifier));
        } else {
            assert!(signature.verifier().is_none());
        }
    }
    Ok(())
}

#[test]
fn reference_rejections_map_to_typed_or_completed_rust_behavior() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let first = fixture
        .cases
        .first()
        .ok_or("signature fixture has no successful case")?;
    for case in &fixture.rejected_cases {
        assert!(!case.reference_error_category.is_empty());
        assert!(!case.reference_error_message.is_empty());
        let category = match case.name.as_str() {
            "short_ed25519_signature" => crypto_error_category(
                &UnindexedSignature::from_raw(SignatureAlgorithm::Ed25519, &[0_u8; 63])
                    .err()
                    .ok_or("short Ed25519 signature was accepted")?,
            ),
            "empty_material" => crypto_error_category(
                &UnindexedSignature::from_qb64("")
                    .err()
                    .ok_or("empty signature material was accepted")?,
            ),
            "qb2_constructor" => {
                let qb2 = decode_hex(&first.qb2_hex)?;
                assert_eq!(UnindexedSignature::from_qb2(&qb2)?.qb64()?, first.qb64);
                "ReferenceUnsupported"
            }
            _ => return Err(format!("unknown rejected fixture case {}", case.name).into()),
        };
        assert_eq!(
            category, case.rust_error_category,
            "category mismatch for {}",
            case.name
        );
    }
    Ok(())
}

#[test]
fn strict_rust_behavior_pins_reference_quirks() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;

    let excess = quirks.excess_raw_truncation;
    let excess_raw = decode_hex(&excess.input_raw_hex)?;
    let retained_raw = decode_hex(&excess.retained_raw_hex)?;
    assert_eq!(
        UnindexedSignature::parse_raw_prefix(SignatureAlgorithm::Ed25519, &excess_raw)?
            .signature()
            .raw()
            .as_slice(),
        retained_raw
    );
    assert_eq!(
        UnindexedSignature::from_raw(SignatureAlgorithm::Ed25519, &retained_raw)?.qb64()?,
        excess.qb64
    );
    let excess_error = UnindexedSignature::from_raw(SignatureAlgorithm::Ed25519, &excess_raw)
        .err()
        .ok_or("excess signature bytes were silently truncated")?;
    assert_eq!(crypto_error_category(&excess_error), excess.rust_error_category);

    let non_signature = quirks.non_signature_code_accepted;
    assert_eq!(non_signature.input_code, "E");
    assert_eq!(non_signature.rust_decision, "reject non-signature derivation codes");
    let retained = decode_hex(&non_signature.retained_raw_hex)?;
    let material = QualifiedMaterial::new(DerivationCode::BLAKE3_256, &retained)?;
    assert_eq!(material.qb64()?, non_signature.qb64);
    let code_error = UnindexedSignature::from_qb64(&non_signature.qb64)
        .err()
        .ok_or("digest material was accepted as a signature")?;
    assert_eq!(crypto_error_category(&code_error), non_signature.rust_error_category);

    let mismatch = quirks.mismatched_verifier_accepted;
    assert_eq!(mismatch.signature_code, "0B");
    assert_eq!(mismatch.verifier_code, "1AAJ");
    assert_eq!(mismatch.rust_decision, "reject verifier/signature algorithm mismatches");
    let signature = UnindexedSignature::from_qb64(
        "0BB43fz0GkIj6INCvq732d7FBZxt3Gw08S1mak9TeRgStsrxiUPEKcMAP9SlJrt6sg5h2pEvTshrYz56rM8IIzcO",
    )?;
    let p256 = VerificationKey::from_qb64("1AAJA-blKBTkTkEEOX_Yq3i3KxZJvcHarPfu_crKVwcfEwvQ")?;
    let mismatch_error = signature
        .with_verifier(p256)
        .err()
        .ok_or("mismatched verifier was accepted")?;
    assert_eq!(crypto_error_category(&mismatch_error), mismatch.rust_error_category);

    let mutable = quirks.mutable_verifier_reassignment;
    assert!(mutable.cleared_verifier_is_undefined);
    assert_eq!(mutable.rust_decision, "use immutable fallible association");
    let verifier = VerificationKey::from_qb64(&mutable.reassigned_verifier_qb64)?;
    let associated = UnindexedSignature::from_qb64(
        "0BB43fz0GkIj6INCvq732d7FBZxt3Gw08S1mak9TeRgStsrxiUPEKcMAP9SlJrt6sg5h2pEvTshrYz56rM8IIzcO",
    )?
    .with_verifier(verifier.clone())?;
    assert_eq!(associated.verifier(), Some(&verifier));
    assert!(associated.without_verifier().verifier().is_none());
    Ok(())
}

fn classification(code: &str) -> Result<SignatureAlgorithm, Box<dyn Error>> {
    match code {
        "0B" => Ok(SignatureAlgorithm::Ed25519),
        "0C" => Ok(SignatureAlgorithm::EcdsaSecp256k1),
        "0I" => Ok(SignatureAlgorithm::EcdsaP256),
        _ => Err(format!("unknown signature fixture code {code}").into()),
    }
}

fn crypto_error_category(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::Cesr { source } => match source.as_ref() {
            CesrError::EmptyInput { .. } => "EmptyInput",
            CesrError::Truncated { .. } => "Truncated",
            CesrError::TrailingMaterial { .. } => "TrailingMaterial",
            _ => "Cesr",
        },
        CryptoError::InvalidSignatureCode { .. } => "InvalidSignatureCode",
        CryptoError::SignatureVerifierMismatch { .. } => "SignatureVerifierMismatch",
        _ => "Other",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex fixture has odd length".into());
    }
    input
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| match pair {
            [high, low] => Ok((decode_nibble(*high)? << 4) | decode_nibble(*low)?),
            _ => Err("hex fixture chunk did not contain two bytes".into()),
        })
        .collect()
}

fn decode_nibble(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err(format!("invalid hex byte 0x{byte:02x}").into()),
    }
}
