//! Exact private-signer fixtures generated by the pinned TypeScript reference.

#![cfg(feature = "crypto")]

use std::error::Error;

use keri_cesr::crypto::{
    CryptoError,
    signature::{IndexedSignature, UnindexedSignature},
    signer::{SignaturePlacement, Signer},
    verifier::KeyTransferability,
};
use keri_cesr::{CesrError, code::DerivationCode, indexer::IndexerCode, matter::QualifiedMaterial};
use serde::Deserialize;

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    algorithm_dependencies: String,
    binary_derivation: String,
    secret_fixture_policy: String,
    cases: Vec<SignerCase>,
    rejected_cases: Vec<RejectedCase>,
    reference_quirks: ReferenceQuirks,
}

#[derive(Debug, Deserialize)]
struct SignerCase {
    name: String,
    transferable: bool,
    seed_code: String,
    seed_raw_hex: String,
    seed_qb64: String,
    seed_qb64_bytes_hex: String,
    seed_qb2_hex: String,
    seed_qb64_round_trip: String,
    verifier_code: String,
    verifier_raw_hex: String,
    verifier_qb64: String,
    serialization_hex: String,
    signature_kind: String,
    signature_code: String,
    signature_index: Option<u32>,
    signature_ondex: Option<u32>,
    signature_raw_hex: String,
    signature_qb64: String,
    signature_qb64_bytes_hex: String,
    signature_qb2_hex: String,
    signature_qb64_round_trip: String,
    verifies_serialization: bool,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    excess_raw_truncation: ExcessRawQuirk,
    current_only_discards_ondex: CurrentOnlyQuirk,
    secret_exposure: SecretExposureQuirk,
}

#[derive(Debug, Deserialize)]
struct ExcessRawQuirk {
    input_raw_hex: String,
    retained_raw_hex: String,
    verifier_qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct CurrentOnlyQuirk {
    requested_index: u32,
    requested_ondex: u32,
    result: SignerCase,
    rust_decision: String,
}

#[derive(Debug, Deserialize)]
struct SecretExposureQuirk {
    reference_raw_and_qb64_are_public: bool,
    rust_decision: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/crypto-signer/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned_and_marks_seed_as_public_test_material() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-12");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/signer.ts",
            "src/keri/core/matter.ts",
            "src/keri/core/verfer.ts",
            "src/keri/core/cigar.ts",
            "src/keri/core/siger.ts",
            "src/keri/core/indexer.ts",
            "test/core/signer.test.ts",
        ]
    );
    assert!(fixture.algorithm_dependencies.contains("libsodium-wrappers-sumo 0.8.4"));
    assert!(fixture.binary_derivation.contains("constructors are unimplemented"));
    assert!(
        fixture
            .secret_fixture_policy
            .contains("never be used as a production secret")
    );
    assert_eq!(fixture.cases.len(), 7);
    assert_eq!(fixture.rejected_cases.len(), 5);
    Ok(())
}

#[test]
fn all_reference_signer_outputs_match_exactly() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        assert!(!case.name.is_empty());
        assert_eq!(case.seed_code, "A");
        let seed = decode_hex(&case.seed_raw_hex)?;
        let seed_qb64_bytes = decode_hex(&case.seed_qb64_bytes_hex)?;
        let seed_qb2 = decode_hex(&case.seed_qb2_hex)?;
        let verifier_raw = decode_hex(&case.verifier_raw_hex)?;
        let serialization = decode_hex(&case.serialization_hex)?;
        let signature_raw = decode_hex(&case.signature_raw_hex)?;
        let signature_qb64_bytes = decode_hex(&case.signature_qb64_bytes_hex)?;
        let signature_qb2 = decode_hex(&case.signature_qb2_hex)?;
        let transferability = transferability(case.transferable);

        let signer = Signer::from_seed(&seed, transferability)?;
        let from_qb64 = Signer::from_qb64(&case.seed_qb64, transferability)?;
        let from_qb64_bytes = Signer::from_qb64_bytes(&seed_qb64_bytes, transferability)?;
        let from_qb2 = Signer::from_qb2(&seed_qb2, transferability)?;
        assert_eq!(signer.code().as_str(), case.seed_code);
        assert_eq!(signer.verifier().code().as_str(), case.verifier_code);
        assert_eq!(signer.verifier().raw(), verifier_raw);
        assert_eq!(signer.verifier().qb64()?, case.verifier_qb64);
        assert_eq!(from_qb64.verifier(), signer.verifier());
        assert_eq!(from_qb64_bytes.verifier(), signer.verifier());
        assert_eq!(from_qb2.verifier(), signer.verifier());
        assert_eq!(case.seed_qb64_round_trip, case.seed_qb64);

        match case.signature_kind.as_str() {
            "unindexed" => {
                assert!(case.signature_index.is_none());
                assert!(case.signature_ondex.is_none());
                let signature = signer.sign_unindexed(&serialization)?;
                assert_eq!(signature.code().as_str(), case.signature_code);
                assert_eq!(signature.raw(), signature_raw.as_slice());
                assert_eq!(signature.qb64()?, case.signature_qb64);
                assert_eq!(signature.qb64_bytes()?, signature_qb64_bytes);
                assert_eq!(signature.qb2()?, signature_qb2);
                assert_eq!(
                    UnindexedSignature::from_qb64(&case.signature_qb64)?,
                    signature.without_verifier()
                );
                assert_eq!(case.signature_qb64_round_trip, case.signature_qb64);
                assert!(case.verifies_serialization);
                signer.verifier().verify(&signature_raw, &serialization)?;
            }
            "indexed" => {
                let index = case.signature_index.ok_or("indexed fixture lacks current index")?;
                let placement = placement_for(&case.signature_code, index, case.signature_ondex)?;
                let signature = signer.sign_indexed(&serialization, placement)?;
                assert_eq!(signature.code().as_str(), case.signature_code);
                assert_eq!(signature.index(), index);
                assert_eq!(signature.other_index(), case.signature_ondex);
                assert_eq!(signature.raw(), signature_raw);
                assert_eq!(signature.qb64()?, case.signature_qb64);
                assert_eq!(signature.qb64_bytes()?, signature_qb64_bytes);
                assert_eq!(signature.qb2()?, signature_qb2);
                assert_eq!(
                    IndexedSignature::from_qb64(&case.signature_qb64)?,
                    signature.without_verifier()
                );
                assert_eq!(case.signature_qb64_round_trip, case.signature_qb64);
                assert!(case.verifies_serialization);
                signer.verifier().verify(&signature_raw, &serialization)?;
            }
            other => return Err(format!("unknown signer fixture signature kind {other}").into()),
        }
    }
    Ok(())
}

#[test]
fn reference_rejections_map_to_typed_or_completed_rust_behavior() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let first = fixture.cases.first().ok_or("signer fixture has no case")?;
    let seed = decode_hex(&first.seed_raw_hex)?;
    for case in &fixture.rejected_cases {
        assert!(!case.reference_error_category.is_empty());
        assert!(!case.reference_error_message.is_empty());
        let category = match case.name.as_str() {
            "short_ed25519_seed" => {
                let short = seed.get(..31).ok_or("fixture seed is shorter than 31 bytes")?;
                crypto_error_category(
                    &Signer::from_seed(short, KeyTransferability::Transferable)
                        .err()
                        .ok_or("short signing seed was accepted")?,
                )
            }
            "unsupported_secp256k1_seed" => unsupported_code_category(DerivationCode::ECDSA_256K1_SEED, &seed)?,
            "invalid_digest_code" => unsupported_code_category(DerivationCode::BLAKE3_256, &seed)?,
            "empty_unsupported_seed" => unsupported_code_category(DerivationCode::ECDSA_256R1_SEED, &seed)?,
            "qb2_constructor" => {
                let qb2 = decode_hex(&first.seed_qb2_hex)?;
                let signer = Signer::from_qb2(&qb2, KeyTransferability::Transferable)?;
                assert_eq!(signer.verifier().qb64()?, first.verifier_qb64);
                "ReferenceUnsupported"
            }
            other => return Err(format!("unknown rejected signer fixture case {other}").into()),
        };
        assert_eq!(
            category, case.rust_error_category,
            "category mismatch for {}",
            case.name
        );
    }
    Ok(())
}

#[test]
fn strict_secret_and_index_behavior_pins_reference_quirks() -> Result<(), Box<dyn Error>> {
    let quirks = fixture()?.reference_quirks;
    let excess = quirks.excess_raw_truncation;
    let input = decode_hex(&excess.input_raw_hex)?;
    let retained = decode_hex(&excess.retained_raw_hex)?;
    let parsed = Signer::parse_seed_prefix(&input, KeyTransferability::Transferable)?;
    assert_eq!(parsed.consumed(), retained.len());
    assert_eq!(parsed.signer().verifier().qb64()?, excess.verifier_qb64);
    let error = Signer::from_seed(&input, KeyTransferability::Transferable)
        .err()
        .ok_or("excess signing-seed bytes were silently truncated")?;
    assert_eq!(crypto_error_category(&error), excess.rust_error_category);

    let current = quirks.current_only_discards_ondex;
    assert_ne!(current.requested_index, current.requested_ondex);
    assert_eq!(current.result.signature_code, IndexerCode::ED25519_CURRENT.as_str());
    assert_eq!(current.result.signature_index, Some(current.requested_index));
    assert_eq!(current.result.signature_ondex, None);
    assert_eq!(
        current.rust_decision,
        "SignaturePlacement::current_list makes a prior-list index unrepresentable"
    );
    let placement = SignaturePlacement::current_list(current.requested_index);
    assert!(placement.is_current_only());
    assert_eq!(placement.prior_index(), None);

    let exposure = quirks.secret_exposure;
    assert!(exposure.reference_raw_and_qb64_are_public);
    assert_eq!(
        exposure.rust_decision,
        "Signer exposes no seed bytes or encoded seed and does not implement Clone, Display, equality, or serialization"
    );
    Ok(())
}

fn transferability(transferable: bool) -> KeyTransferability {
    if transferable {
        KeyTransferability::Transferable
    } else {
        KeyTransferability::NonTransferable
    }
}

fn placement_for(code: &str, index: u32, prior: Option<u32>) -> Result<SignaturePlacement, Box<dyn Error>> {
    match code {
        "A" | "2A" => Ok(SignaturePlacement::both_lists_with_prior(
            index,
            prior.ok_or("both-list fixture lacks prior index")?,
        )),
        "B" | "2B" => {
            if prior.is_some() {
                Err("current-only fixture unexpectedly has a prior index".into())
            } else {
                Ok(SignaturePlacement::current_list(index))
            }
        }
        other => Err(format!("unknown indexed signer fixture code {other}").into()),
    }
}

fn unsupported_code_category(code: DerivationCode, seed: &[u8]) -> Result<&'static str, Box<dyn Error>> {
    let material = QualifiedMaterial::new(code, seed)?;
    let error = Signer::from_qb64(&material.qb64()?, KeyTransferability::Transferable)
        .err()
        .ok_or("unsupported signing seed code was accepted")?;
    Ok(crypto_error_category(&error))
}

fn crypto_error_category(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::Cesr { source } => match source.as_ref() {
            CesrError::Truncated { .. } => "Truncated",
            CesrError::TrailingMaterial { .. } => "TrailingMaterial",
            _ => "Cesr",
        },
        CryptoError::InvalidSigningCode { .. } => "InvalidSigningCode",
        CryptoError::UnsupportedSigningAlgorithm { .. } => "UnsupportedSigningAlgorithm",
        _ => "Other",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex fixture has odd length".into());
    }
    input
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| match pair {
            [high, low] => Ok((decode_nibble(*high)? << 4) | decode_nibble(*low)?),
            _ => Err("hex fixture chunk was not two bytes".into()),
        })
        .collect()
}

fn decode_nibble(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err("hex fixture contains a non-hexadecimal byte".into()),
    }
}
