//! Exact public-verification-key fixtures generated by the pinned TypeScript reference.

#![cfg(feature = "crypto")]

use std::error::Error;

use keri_cesr::crypto::{
    CryptoError,
    verifier::{
        ED25519_PUBLIC_KEY_SIZE, KeyTransferability, P256_PUBLIC_KEY_SIZE, VerificationAlgorithm, VerificationKey,
    },
};
use keri_cesr::{CesrError, code::DerivationCode, matter::QualifiedMaterial};
use serde::{Deserialize, Deserializer};

const REFERENCE_SHA: &str = "ae92eceb8e776ad57669707bff7f84db9390b711";

#[derive(Debug, Deserialize)]
struct Fixture {
    schema_version: u8,
    upstream: String,
    reference_sha: String,
    generated_on: String,
    sources: Vec<String>,
    algorithm_dependencies: String,
    binary_derivation: String,
    cases: Vec<VerifierCase>,
    rejected_cases: Vec<RejectedCase>,
    verification_edges: VerificationEdges,
    safe_p256_divergence: SafeP256Divergence,
    reference_quirks: ReferenceQuirks,
}

#[derive(Debug, Deserialize)]
struct VerifierCase {
    name: String,
    code: String,
    raw_hex: String,
    qb64: String,
    qb64_bytes_hex: String,
    qb2_hex: String,
    qb64_round_trip: String,
    serialization_hex: String,
    signature_hex: String,
    verifies_serialization: bool,
    verifies_changed_serialization: bool,
}

#[derive(Debug, Deserialize)]
struct RejectedCase {
    name: String,
    reference_error_category: String,
    reference_error_message: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct VerificationEdges {
    p256_signature_is_high_s: bool,
    p256_high_s_signature_hex: String,
    p256_low_s_signature_hex: String,
    p256_accepts_high_s: bool,
    p256_accepts_low_s: bool,
    ed25519_truncated_signature: ReferenceVerificationResult,
    p256_truncated_signature: ReferenceVerificationResult,
}

#[derive(Debug, Deserialize)]
struct ReferenceVerificationResult {
    result: Option<bool>,
    error_category: Option<String>,
}

#[derive(Debug, Deserialize)]
struct SafeP256Divergence {
    decision: String,
    signature_hex: String,
    signature_is_high_s: ExpectedBoolean,
    high_s_signature_hex: String,
    noble_full_message_verifies: ExpectedBoolean,
    noble_full_message_verifies_changed: ExpectedBoolean,
    noble_full_message_verifies_high_s: ExpectedBoolean,
    pinned_verfer_verifies_safe_signature: ExpectedBoolean,
    safe_mode_verifies_pinned_signature: ExpectedBoolean,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ExpectedBoolean {
    False,
    True,
}

impl ExpectedBoolean {
    const fn is_true(self) -> bool {
        matches!(self, Self::True)
    }
}

impl<'de> Deserialize<'de> for ExpectedBoolean {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(if bool::deserialize(deserializer)? {
            Self::True
        } else {
            Self::False
        })
    }
}

#[derive(Debug, Deserialize)]
struct ReferenceQuirks {
    excess_raw_truncation: ExcessRawQuirk,
    weak_ed25519_key_accepted_at_construction: InvalidKeyQuirk,
    invalid_p256_key_accepted_at_construction: InvalidKeyQuirk,
}

#[derive(Debug, Deserialize)]
struct ExcessRawQuirk {
    input_raw_hex: String,
    retained_raw_hex: String,
    qb64: String,
    rust_error_category: String,
}

#[derive(Debug, Deserialize)]
struct InvalidKeyQuirk {
    raw_hex: String,
    qb64: String,
    verification_result: bool,
    rust_error_category: String,
    rust_decision: String,
}

fn fixture() -> Result<Fixture, serde_json::Error> {
    serde_json::from_str(include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/fixtures/crypto-verifier/v1.json"
    )))
}

#[test]
fn fixture_metadata_is_pinned() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    assert_eq!(fixture.schema_version, 1);
    assert_eq!(fixture.upstream, "https://github.com/WebOfTrust/signify-ts.git");
    assert_eq!(fixture.reference_sha, REFERENCE_SHA);
    assert_eq!(fixture.generated_on, "2026-08-11");
    assert_eq!(
        fixture.sources,
        [
            "src/keri/core/verfer.ts",
            "src/keri/core/matter.ts",
            "test/core/verfer.test.ts",
        ]
    );
    assert!(fixture.algorithm_dependencies.contains("libsodium-wrappers-sumo 0.8.4"));
    assert!(fixture.algorithm_dependencies.contains("@noble/curves 1.9.7"));
    assert!(fixture.binary_derivation.contains("Matter._bexfil"));
    Ok(())
}

#[test]
fn reference_key_material_matches_in_every_domain() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        let (algorithm, transferability) = classification(&case.code)?;
        let raw = decode_hex(&case.raw_hex)?;
        let qb64_bytes = decode_hex(&case.qb64_bytes_hex)?;
        let qb2 = decode_hex(&case.qb2_hex)?;
        let key = VerificationKey::from_raw(algorithm, transferability, &raw)?;

        assert_eq!(key.algorithm(), algorithm, "algorithm mismatch for {}", case.name);
        assert_eq!(
            key.transferability(),
            transferability,
            "transferability mismatch for {}",
            case.name
        );
        assert_eq!(key.is_transferable(), transferability.is_transferable());
        assert_eq!(key.code().as_str(), case.code, "code mismatch for {}", case.name);
        assert_eq!(key.raw(), raw, "raw mismatch for {}", case.name);
        assert_eq!(key.qb64()?, case.qb64, "qb64 mismatch for {}", case.name);
        assert_eq!(key.qb64_bytes()?, qb64_bytes, "qb64 bytes mismatch for {}", case.name);
        assert_eq!(key.qb2()?, qb2, "qb2 mismatch for {}", case.name);
        assert_eq!(case.qb64_round_trip, case.qb64);
        assert_eq!(VerificationKey::from_qb64(&case.qb64)?, key);
        assert_eq!(VerificationKey::from_qb64_bytes(&qb64_bytes)?, key);
        assert_eq!(VerificationKey::from_qb2(&qb2)?, key);
    }
    Ok(())
}

#[test]
fn ed25519_reference_signatures_match_and_p256_defect_is_rejected() -> Result<(), Box<dyn Error>> {
    for case in fixture()?.cases {
        let serialization = decode_hex(&case.serialization_hex)?;
        let signature = decode_hex(&case.signature_hex)?;
        let key = VerificationKey::from_qb64(&case.qb64)?;
        assert!(case.verifies_serialization);

        match key.algorithm() {
            VerificationAlgorithm::Ed25519 => {
                key.verify(&signature, &serialization)?;
                assert!(!case.verifies_changed_serialization);
                let changed = changed_serialization(&serialization)?;
                assert!(matches!(
                    key.verify(&signature, &changed),
                    Err(CryptoError::VerificationFailed { .. })
                ));
            }
            VerificationAlgorithm::EcdsaP256 => {
                assert!(case.verifies_changed_serialization);
                assert!(matches!(
                    key.verify(&signature, &serialization),
                    Err(CryptoError::VerificationFailed { .. })
                ));
            }
            _ => return Err("fixture selected an unknown verification algorithm".into()),
        }
    }
    Ok(())
}

#[test]
fn safe_p256_sha256_vector_matches_pinned_noble_primitive() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let safe = fixture.safe_p256_divergence;
    assert_eq!(safe.decision, "SHA-256 over the complete serialization");
    assert!(!safe.signature_is_high_s.is_true());
    assert!(safe.noble_full_message_verifies.is_true());
    assert!(!safe.noble_full_message_verifies_changed.is_true());
    assert!(safe.noble_full_message_verifies_high_s.is_true());
    assert!(!safe.pinned_verfer_verifies_safe_signature.is_true());
    assert!(!safe.safe_mode_verifies_pinned_signature.is_true());

    let low_signature = decode_hex(&safe.signature_hex)?;
    let high_signature = decode_hex(&safe.high_s_signature_hex)?;
    for case in fixture
        .cases
        .iter()
        .filter(|case| case.code == "1AAI" || case.code == "1AAJ")
    {
        let key = VerificationKey::from_qb64(&case.qb64)?;
        let serialization = decode_hex(&case.serialization_hex)?;
        key.verify(&low_signature, &serialization)?;
        key.verify(&high_signature, &serialization)?;
        let changed = changed_serialization(&serialization)?;
        assert!(matches!(
            key.verify(&low_signature, &changed),
            Err(CryptoError::VerificationFailed { .. })
        ));
    }
    Ok(())
}

#[test]
fn reference_rejections_map_to_typed_or_completed_rust_behavior() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let first = fixture.cases.first().ok_or("verifier fixture has no successful case")?;
    for case in &fixture.rejected_cases {
        assert!(!case.reference_error_category.is_empty());
        assert!(!case.reference_error_message.is_empty());
        let category = match case.name.as_str() {
            "unsupported_secp256k1" => {
                let material = QualifiedMaterial::new(DerivationCode::ECDSA_256K1, &[2_u8; P256_PUBLIC_KEY_SIZE])?;
                crypto_error_category(
                    &VerificationKey::from_qb64(&material.qb64()?)
                        .err()
                        .ok_or("secp256k1 verifier was accepted")?,
                )
            }
            "short_ed25519_key" => crypto_error_category(
                &VerificationKey::from_raw(
                    VerificationAlgorithm::Ed25519,
                    KeyTransferability::Transferable,
                    &[0_u8; ED25519_PUBLIC_KEY_SIZE - 1],
                )
                .err()
                .ok_or("short Ed25519 key was accepted")?,
            ),
            "digest_code" => {
                let material = QualifiedMaterial::new(DerivationCode::BLAKE3_256, &[0_u8; ED25519_PUBLIC_KEY_SIZE])?;
                crypto_error_category(
                    &VerificationKey::from_qb64(&material.qb64()?)
                        .err()
                        .ok_or("digest code was accepted as a verifier")?,
                )
            }
            "qb2_constructor" => {
                let qb2 = decode_hex(&first.qb2_hex)?;
                assert_eq!(VerificationKey::from_qb2(&qb2)?.qb64()?, first.qb64);
                "ReferenceUnsupported"
            }
            _ => return Err(format!("unknown rejected fixture case {}", case.name).into()),
        };
        assert_eq!(
            category, case.rust_error_category,
            "category mismatch for {}",
            case.name
        );
    }
    Ok(())
}

#[test]
fn malformed_signatures_and_invalid_keys_are_strictly_handled() -> Result<(), Box<dyn Error>> {
    let fixture = fixture()?;
    let edges = fixture.verification_edges;
    assert!(edges.p256_signature_is_high_s);
    assert!(edges.p256_accepts_high_s);
    assert!(edges.p256_accepts_low_s);
    assert_eq!(decode_hex(&edges.p256_high_s_signature_hex)?.len(), 64);
    assert_eq!(decode_hex(&edges.p256_low_s_signature_hex)?.len(), 64);
    assert_eq!(edges.ed25519_truncated_signature.result, None);
    assert_eq!(
        edges.ed25519_truncated_signature.error_category.as_deref(),
        Some("TypeError")
    );
    assert_eq!(edges.p256_truncated_signature.result, Some(false));
    assert_eq!(edges.p256_truncated_signature.error_category, None);

    for case in &fixture.cases {
        let key = VerificationKey::from_qb64(&case.qb64)?;
        assert!(matches!(
            key.verify(&[0_u8; 63], b"message"),
            Err(CryptoError::InvalidSignatureLength { actual: 63, .. })
        ));
    }

    let quirks = fixture.reference_quirks;
    let excess = quirks.excess_raw_truncation;
    let excess_raw = decode_hex(&excess.input_raw_hex)?;
    let retained_raw = decode_hex(&excess.retained_raw_hex)?;
    assert_eq!(
        VerificationKey::parse_raw_prefix(
            VerificationAlgorithm::Ed25519,
            KeyTransferability::Transferable,
            &excess_raw,
        )?
        .key()
        .raw(),
        retained_raw
    );
    assert_eq!(
        VerificationKey::from_raw(
            VerificationAlgorithm::Ed25519,
            KeyTransferability::Transferable,
            &retained_raw,
        )?
        .qb64()?,
        excess.qb64
    );
    let error = VerificationKey::from_raw(
        VerificationAlgorithm::Ed25519,
        KeyTransferability::Transferable,
        &excess_raw,
    )
    .err()
    .ok_or("excess raw key was silently truncated")?;
    assert_eq!(crypto_error_category(&error), excess.rust_error_category);

    assert_invalid_key_quirk(
        &quirks.weak_ed25519_key_accepted_at_construction,
        VerificationAlgorithm::Ed25519,
    )?;
    assert_invalid_key_quirk(
        &quirks.invalid_p256_key_accepted_at_construction,
        VerificationAlgorithm::EcdsaP256,
    )?;
    Ok(())
}

fn assert_invalid_key_quirk(quirk: &InvalidKeyQuirk, algorithm: VerificationAlgorithm) -> Result<(), Box<dyn Error>> {
    assert!(!quirk.verification_result);
    assert!(!quirk.qb64.is_empty());
    assert!(!quirk.rust_decision.is_empty());
    let raw = decode_hex(&quirk.raw_hex)?;
    let error = VerificationKey::from_raw(algorithm, KeyTransferability::Transferable, &raw)
        .err()
        .ok_or("invalid reference key was accepted")?;
    assert_eq!(crypto_error_category(&error), quirk.rust_error_category);
    Ok(())
}

fn classification(code: &str) -> Result<(VerificationAlgorithm, KeyTransferability), Box<dyn Error>> {
    match code {
        "B" => Ok((VerificationAlgorithm::Ed25519, KeyTransferability::NonTransferable)),
        "D" => Ok((VerificationAlgorithm::Ed25519, KeyTransferability::Transferable)),
        "1AAI" => Ok((VerificationAlgorithm::EcdsaP256, KeyTransferability::NonTransferable)),
        "1AAJ" => Ok((VerificationAlgorithm::EcdsaP256, KeyTransferability::Transferable)),
        _ => Err(format!("unknown verifier fixture code {code}").into()),
    }
}

fn changed_serialization(serialization: &[u8]) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut changed = serialization.to_vec();
    let last = changed.last_mut().ok_or("fixture serialization is empty")?;
    *last ^= 1;
    Ok(changed)
}

fn crypto_error_category(error: &CryptoError) -> &'static str {
    match error {
        CryptoError::Cesr { source } => match source.as_ref() {
            CesrError::Truncated { .. } => "Truncated",
            CesrError::TrailingMaterial { .. } => "TrailingMaterial",
            _ => "Cesr",
        },
        CryptoError::InvalidVerificationCode { .. } => "InvalidVerificationCode",
        CryptoError::UnsupportedVerificationAlgorithm { .. } => "UnsupportedVerificationAlgorithm",
        CryptoError::InvalidVerificationKey { .. } => "InvalidVerificationKey",
        CryptoError::InvalidSignatureLength { .. } => "InvalidSignatureLength",
        CryptoError::InvalidSignatureEncoding { .. } => "InvalidSignatureEncoding",
        CryptoError::VerificationFailed { .. } => "VerificationFailed",
        _ => "Other",
    }
}

fn decode_hex(input: &str) -> Result<Vec<u8>, Box<dyn Error>> {
    if !input.len().is_multiple_of(2) {
        return Err("hex fixture has odd length".into());
    }
    input
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| match pair {
            [high, low] => Ok((decode_nibble(*high)? << 4) | decode_nibble(*low)?),
            _ => Err("hex fixture chunk did not contain two bytes".into()),
        })
        .collect()
}

fn decode_nibble(byte: u8) -> Result<u8, Box<dyn Error>> {
    match byte {
        b'0'..=b'9' => Ok(byte - b'0'),
        b'a'..=b'f' => Ok(byte - b'a' + 10),
        b'A'..=b'F' => Ok(byte - b'A' + 10),
        _ => Err(format!("invalid hex byte 0x{byte:02x}").into()),
    }
}
